import { Link } from "react-router-dom";
import { AlertTriangle, ArrowLeft } from "lucide-react";

export default function Disclaimer() {
  return (
    <div className="min-h-screen bg-slate-50 flex items-center justify-center p-6">
      <div className="w-full max-w-2xl bg-white rounded-3xl p-8 shadow-xl border border-slate-100">
        <div className="flex items-center gap-4 border-b pb-6">
          <div className="p-3 bg-amber-50 text-amber-600 rounded-2xl">
            <AlertTriangle size={32} />
          </div>
          <div>
            <h1 className="text-3xl font-bold text-slate-900">Legal Disclaimer</h1>
            <p className="text-slate-500 text-sm">Please read carefully before using ARAM.</p>
          </div>
        </div>

        <div className="mt-6 space-y-4 text-slate-600 leading-relaxed">
          <p className="font-semibold text-slate-800 text-lg">
            ARAM provides preliminary complaint guidance only. It does not replace police, court, lawyer, or official authority.
          </p>
          <p>
            The information, content, and triage output generated by the ARAM platform (including AI classifications, priority ratings, and recommended documents) are for guidance purposes only. They do not constitute formal legal advice, legal opinions, or professional consultations.
          </p>
          <p>
            ARAM is an aid dispatch and triage software designed to direct citizens to relevant legal departments and assist volunteer helpers. We do not guarantee the resolution of complaints, nor do we represent any judicial body or law enforcement agency.
          </p>
          <p>
            By using this platform, you agree that ARAM and its developers are not liable for any action taken or not taken based on the output of this application. For complex legal cases, consult a certified legal advocate or approach your nearest District Legal Services Authority (DLSA).
          </p>
        </div>

        <div className="mt-8 pt-6 border-t flex justify-end">
          <Link
            to="/"
            className="flex items-center gap-2 px-6 h-12 bg-slate-900 text-white rounded-xl hover:bg-slate-800 font-medium transition"
          >
            <ArrowLeft size={16} />
            Back to Home
          </Link>
        </div>
      </div>
    </div>
  );
}
