# Run with: mvn spring-boot:run -Dspring-boot.run.profiles=mysql
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/aram_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata}
spring.datasource.username=${DB_USER:aram}
spring.datasource.password=${DB_PASSWORD:your_desired_password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.globally_quoted_identifiers=false

# Flyway Configuration
spring.flyway.enabled=true

server.address=0.0.0.0
server.port=8082
