package com.aram.legalaid.enums;

public enum EmailTemplateType {
    EMAIL_VERIFICATION_OTP,
    PASSWORD_RESET_OTP,
    PASSWORD_CHANGED,
    ACCOUNT_VERIFIED,
    COMPLAINT_SUBMITTED,
    COMPLAINT_STATUS_UPDATED,
    GUIDE_ASSIGNED,
    GUIDE_REQUEST_RECEIVED,
    GUIDE_NEW_CASE,
    CASE_RESOLVED,
    ESCALATION_ALERT,
    GUIDE_INVITATION,
    ADMIN_INVITATION,
    SECURITY_ALERT
}
