import React, { createContext, useContext, useState } from "react";

const LanguageContext = createContext();

export const availableLanguages = [
  { code: "en-IN", label: "English", nativeLabel: "English" },
  { code: "ta-IN", label: "Tamil", nativeLabel: "தமிழ்" },
  { code: "hi-IN", label: "Hindi", nativeLabel: "हिंदी" }
];

export const translations = {
  "en-IN": {
    nav: {
      home: "Home",
      about: "About",
      services: "Services",
      howItWorks: "How ARAM Works",
      trackCase: "Track Case",
      trackGrievance: "Track Grievance",
      contact: "Contact",
      signIn: "Sign In",
      dashboard: "Dashboard",
      askAi: "Ask ARAM AI"
    },
    hero: {
      badge: "CIVIC LEGAL AID & GRIEVANCE TRIAGE",
      eyebrow: "Accessible Justice for Every Citizen",
      title1: "Your Rights. Our Support.",
      title2: "A Fairer Tomorrow.",
      subtitle: "ARAM helps citizens understand legal information, identify the right authorities, organize supporting evidence, and connect with verified legal guides — in Tamil, English, and Hindi.",
      askAi: "Ask ARAM AI",
      fileGrievance: "File a Grievance",
      trackCase: "Track My Case",
      speakProblem: "Speak Problem",
      listening: "Listening... Click to Finish",
      uploadDoc: "Upload Document",
      connectGuide: "Connect Guide",
      noLegalFees: "No Legal Fees",
      piiPrivacy: "Strict PII Privacy",
      dlsaAligned: "Tamil Nadu DLSA Aligned"
    },
    trustStrip: {
      multilingual: "Multilingual Legal Assistance",
      multilingualDesc: "Tamil • English • Hindi",
      verified: "Grounded in Verified Statutes",
      verifiedDesc: "Certified Indian law provisions",
      humanSupport: "Human Guide & DLSA Support",
      humanSupportDesc: "Accredited legal escalation",
      districtAware: "District-Aware Guidance",
      districtAwareDesc: "All 38 Tamil Nadu districts",
      liveRegistry: "Statewide Live Civic Registry Data",
      platformIndicators: "Statewide Civic Platform Indicators",
      verifiedRealTime: "Verified Real-Time Counts",
      tnGovInitiative: "Government of Tamil Nadu • Legal Aid Initiative",
      totalComplaints: "Total Complaints",
      acrossDistricts: "Across {count} Districts",
      activeInReview: "Active in Review",
      underDlsa: "Under DLSA Process",
      resolvedCases: "Resolved Cases",
      citizensHelped: "Citizens Helped",
      legalGuides: "Legal Guides",
      acrossTn: "Across Tamil Nadu",
      quote: "“Access to justice strengthens democracy.”",
      quoteAuthor: "— NALSA (National Legal Services)"
    },
    waysToGetHelp: {
      tag: "Ways to Get Help",
      title: "Choose How You Want to Begin",
      subtitle: "Every citizen communicates differently. Select the method most comfortable for you.",
      civicAssistance: "Free Civic Assistance • No Hidden Charges",
      speakTitle: "Speak",
      speakSubtitle: "Voice-First Assistance",
      speakDesc: "Describe your issue naturally in Tamil, English, or Hindi using your voice.",
      speakAction: "Tap to Speak",
      speakListening: "Listening...",
      speakBadge: "Tamil • Hindi • English",
      typeTitle: "Type",
      typeSubtitle: "Interactive AI Chat",
      typeDesc: "Explain your issue in your own words. Receive statutory triage and legal clarity.",
      typeAction: "Chat with AI",
      typeBadge: "24/7 Available",
      uploadTitle: "Upload",
      uploadSubtitle: "Document Evidence",
      uploadDesc: "Share relevant documents, notices, sale deeds, or police complaint copies.",
      uploadAction: "Inspect Documents",
      uploadBadge: "Deep OCR Ready",
      connectTitle: "Connect",
      connectSubtitle: "Human Legal Guides",
      connectDesc: "Get connected with an accredited District Legal Guide when human support is needed.",
      connectAction: "Find a Guide",
      connectBadge: "DLSA Accredited"
    },
    aiHuman: {
      tag: "AI + Human Synergy",
      title: "AI When Possible. Human When Necessary.",
      subtitle: "The speed of intelligent legal triage combined with the trusted judgment of certified human legal guides.",
      desc1: "ARAM AI immediately organizes your dispute, identifies applicable statutory sections, prepares required evidence checklists, and checks document readiness.",
      desc2: "When your matter requires formal legal drafting, statutory filing, or DLSA representation, verified human Legal Guides and accredited advocates step in directly to support you.",
      bullet1: "Instant 24x7 preliminary statutory analysis and rights explanation",
      bullet2: "Zero automated dismissal — every complex case has human escalation",
      bullet3: "Direct coordination with Taluk and District Legal Services Authorities (DLSA)",
      aiTitle: "AI Assistance",
      aiSubtitle: "Immediate 24/7 Digital First-Aid",
      humanTitle: "Human Support",
      humanSubtitle: "Accredited DLSA & Legal Guides",
      startAi: "Start AI Assessment",
      requestGuide: "Request Legal Guide"
    },
    immediateHelp: {
      tag: "Emergency & Statutory Support",
      title: "Need Immediate Assistance?",
      subtitle: "Official government helplines for urgent emergencies, women safety, cybercrime, and free legal aid.",
      emergency: "Emergency Services",
      emergencySub: "Police, Fire & Ambulance (24x7)",
      women: "Women Helpline",
      womenSub: "Safety & Domestic Violence (24x7)",
      cyber: "Cyber Crime Helpline",
      cyberSub: "National Financial Fraud Reporting",
      legalAid: "NALSA Legal Aid",
      legalAidSub: "Free Legal Aid & DLSA Services",
      badgeEmergency: "National Emergency",
      badgeWomen: "Women Safety",
      badgeCyber: "Cyber Fraud",
      badgeLegalAid: "Free Legal Aid"
    },
    howItWorks: {
      tag: "Citizen Journey",
      title: "How ARAM Helps",
      subtitle: "From your first question to accredited legal escalation — simple, transparent, and grounded in law.",
      notice: "ARAM is an administrative and legal aid accessibility aid, not an automated court of law. All formal representations proceed through accredited human legal guides and statutory authorities.",
      phase: "Phase",
      step1Title: "Tell ARAM",
      step1Subtitle: "Multi-Modal Input",
      step1Desc: "Speak, type, or upload your issue naturally in Tamil, English, or Hindi.",
      step2Title: "Understand Your Case",
      step2Subtitle: "Statutory Triage",
      step2Desc: "ARAM analyzes the facts, identifies applicable statutory sections, and highlights key issues.",
      step3Title: "Find Verified Guidance",
      step3Subtitle: "Grounding & Evidence",
      step3Desc: "Relevant verified legal provisions, authority routing, and evidence checklists are structured.",
      step4Title: "Human Support",
      step4Subtitle: "DLSA & Legal Guides",
      step4Desc: "Cases seamlessly move toward accredited legal guides and District Legal Services Authorities.",
      step5Title: "Track Your Case",
      step5Subtitle: "Full Transparency",
      step5Desc: "Citizens follow live milestone progress, receive WhatsApp/SMS updates, and download official PDFs."
    },
    features: {
      tag: "Engineered for Justice",
      title: "How ARAM AI Protects Your Legal Rights",
      subtitle: "Strictly grounded against certified Indian law provisions with zero synthetic hallucination.",
      f1Title: "11-Part Structured Legal Triage",
      f1Desc: "Every query receives grounded statutory citation, section applicability, next steps, document checklists, and DLSA authority routing.",
      f2Title: "Multilingual Voice Assistant",
      f2Desc: "Direct voice input in Tamil (தமிழ்), Hindi (हिंदी), and English for hands-free grievance registration and guidance.",
      f3Title: "OCR Document Readiness Checker",
      f3Desc: "Automated optical character verification of sale deeds, partition agreements, and notices with legal readiness scoring.",
      f4Title: "Certified Legal Guide Workflow",
      f4Desc: "Seamless escalation from AI triage to verified local paralegal guides and District Legal Services Authorities (DLSA)."
    },
    about: {
      tag: "Our Mission",
      title: "Democratizing Legal Rights for Every Citizen",
      desc1: "ARAM (அறம்) is built on the fundamental belief that access to justice should not be barred by language, geography, or economic standing.",
      desc2: "By connecting citizens directly with grounded statutory knowledge and verified legal guides, ARAM ensures equitable legal awareness.",
      commitmentsTitle: "ARAM Core Commitments",
      c1: "Zero Hallucination: All legal advice is verified against certified statutes.",
      c2: "Privacy Protection: Automatic PII masking of Aadhaar and personal details.",
      c3: "Official Email Gateway: Centralized communication from ouraramsupport@gmail.com."
    },
    whoCanUse: {
      tag: "Stakeholder Ecosystem",
      title: "Who Can Use ARAM",
      subtitle: "Designed to connect every stakeholder in public legal awareness and dispute resolution.",
      tagPublic: "Public Access",
      tagAssistance: "Case Assistance",
      tagAuthority: "Authority Triage",
      tagGovernance: "Governance",
      u1Title: "Citizens",
      u1Desc: "Explain grievances in your preferred language, understand statutory rights, organize evidence, and track case progress from home.",
      u2Title: "Legal Guides & Volunteers",
      u2Desc: "Authorized paralegals and legal volunteers who review AI triage, assist citizens with petition drafting, and provide field guidance.",
      u3Title: "Government Officials",
      u3Desc: "District department officers and DLSA representatives who receive structured petitions with verified evidence for statutory resolution.",
      u4Title: "Platform Administrators",
      u4Desc: "Supervisors monitoring district-wide grievance resolution, audit trails, system performance, and legal service quality."
    },
    cta: {
      title: "Ready to Understand Your Rights?",
      subtitle: "Ask your first legal question, verify evidence documents, or connect with a verified legal guide today.",
      button: "Start Free Legal Triage",
      tag: "Begin Your Legal Resolution",
      heading: "Not sure where to start?",
      desc: "Tell ARAM what happened. We'll help you understand your rights, prepare your documents, and find the next step.",
      askAi: "Ask ARAM AI",
      fileGrievance: "File a Grievance",
      footerNote: "Free Public Service • Confidential • Grounded in Indian Law"
    },
    immediateHelp: {
      tag: "Emergency & Statutory Support",
      title: "Need Immediate Assistance?",
      subtitle: "Official government helplines for urgent emergencies, women safety, cybercrime, and free legal aid.",
      emergency: "Emergency Services",
      emergencySub: "Police, Fire & Ambulance (24x7)",
      badgeEmergency: "National Emergency",
      women: "Women Helpline",
      womenSub: "Safety & Domestic Violence (24x7)",
      badgeWomen: "Women Safety",
      cyber: "Cyber Crime Helpline",
      cyberSub: "National Financial Fraud Reporting",
      badgeCyber: "Cyber Fraud",
      legalAid: "NALSA Legal Aid",
      legalAidSub: "Free Legal Aid & DLSA Services",
      badgeLegalAid: "Free Legal Aid",
      tapToCall: "Tap to Call {number}"
    },
    civicFeatures: {
      petitionTitle: "Ready-to-File Legal Representation",
      petitionSub: "Formal statutory petition draft formatted for submission to the competent authority.",
      btnGeneratePetition: "Generate Formal Petition Draft",
      btnPrintPetition: "Print Petition Document",
      btnCopyPetition: "Copy Petition Text",
      langTamil: "Draft in Tamil (தமிழ்)",
      langEnglish: "Draft in English",
      petitionFrom: "From (Petitioner):",
      petitionTo: "To (Competent Authority):",
      petitionSubject: "Subject:",
      petitionFacts: "Statement of Facts & Grievance:",
      petitionProvisions: "Statutory Provisions & Citations:",
      petitionPrayer: "Prayer / Relief Sought:",
      petitionVerification: "I hereby solemnly declare and verify that the facts stated above are true and correct to the best of my knowledge and belief.",
      petitionSignature: "Signature / Thumb Impression of Petitioner",
      
      sec12Title: "NALSA Section 12 Legal Aid Eligibility",
      sec12Sub: "Verify if you qualify for 100% free advocate representation under the Legal Services Authorities Act, 1987.",
      btnCheckSec12: "Check Free Legal Aid Eligibility",
      sec12Q1: "Are you a woman or a child (under 18)?",
      sec12Q2: "Do you belong to Scheduled Caste (SC) or Scheduled Tribe (ST)?",
      sec12Q3: "Are you a person with disability, victim of human trafficking, or natural disaster?",
      sec12Q4: "Is your annual family income less than ₹3,00,000 (statutory limit in Tamil Nadu)?",
      sec12Eligible: "Qualified for 100% Free Legal Aid",
      sec12EligibleDesc: "You are legally entitled to free legal counsel and DLSA panel lawyer representation at government expense.",
      sec12NotEligible: "Standard Legal Guidance Mode",
      sec12NotEligibleDesc: "While you may not qualify for a free court advocate under Section 12, ARAM AI guidance and paralegal triage remain 100% free.",
      
      ratingTitle: "Citizen Satisfaction & Resolution Feedback",
      ratingSub: "Official review of the legal assistance provided for your grievance.",
      rateExperience: "How would you rate the resolution of your grievance?",
      wasHelpful: "Was the guidance provided by the Legal Guide helpful?",
      yesHelpful: "Yes, Helpful",
      noHelpful: "Needs Improvement",
      feedbackPlaceholder: "Add any comments or observations regarding the resolution...",
      btnSubmitRating: "Confirm Resolution & Submit Feedback",
      lowRatingAlert: "Dissatisfied with this resolution?",
      lowRatingDesc: "If your grievance was not resolved satisfactorily, you have the statutory right to appeal and reopen this case for District Admin review.",
      btnAppealReopen: "File Formal Appeal / Reopen Case",
      alreadyRated: "You have verified and rated this resolution ({stars}/5 Stars)",
      
      appointmentTitle: "Request 10-Min Guidance Call",
      appointmentSub: "Schedule a telephonic or voice consultation with your assigned Legal Guide.",
      btnRequestCall: "Request Guidance Call",
      selectMode: "Consultation Mode",
      modePhone: "Phone Call (Mobile)",
      modeApp: "In-App Audio Consultation",
      modeWa: "WhatsApp Voice/Text Guidance",
      selectSlot: "Preferred Time Window",
      slotMorning: "Morning (10:00 AM – 01:00 PM)",
      slotAfternoon: "Afternoon (02:00 PM – 05:00 PM)",
      slotEvening: "Evening (05:00 PM – 08:00 PM)",
      appointmentNote: "Specific question or case aspect you want to discuss",
      btnSubmitAppointment: "Confirm Call Request",
      appointmentActive: "Guidance Call Requested",
      
      lokAdalatTitle: "Eligible for Lok Adalat Pre-Litigation",
      lokAdalatDesc: "This dispute can be resolved amicably through the National / Taluk Lok Adalat with zero court fees and final decree status under Section 21 of LSA Act 1987.",
      
      atrTitle: "Official Action Taken Report (ATR)",
      atrSub: "Statutory closure memo issued by the assigned Legal Guide / District Authority.",
      atrVerified: "Statutory Verification Complete"
    },
    sidebar: {
      portalTitle: "Legal Aid Portal",
      dashboard: "Dashboard",
      askAi: "Ask ARAM AI",
      submitGrievance: "Submit Grievance",
      myGrievances: "My Grievances",
      documentsEvidence: "Documents & Evidence",
      trackStatus: "Track Status",
      supportSettings: "Support & Settings",
      notifications: "Notifications",
      helpRights: "Help & Rights Guide",
      profileSettings: "Profile & Settings",
      signOut: "Sign Out"
    },
    topbar: {
      searchCitizen: "Ask ARAM AI legal questions (e.g., land title, RTI, 498A)...",
      searchAdmin: "Search grievances across all 38 districts (ID, citizen, keyword)...",
      searchGuide: "Search assigned cases or legal topics...",
      lightMode: "Switch to Light Mode",
      darkMode: "Switch to Dark Mode",
      notifications: "Notifications"
    },
    citizenDashboard: {
      portalBadge: "Tamil Nadu Public Legal Aid & Grievance Portal",
      heroGreeting: "Hello, {name}. How can ARAM assist you today?",
      heroDescription: "Describe any grievance, legal issue, or dispute in Tamil, English, or Hindi to receive immediate verified guidance, document requirements, and assigned legal guide assistance.",
      askLegalAssistant: "Ask ARAM Legal Assistant",
      speakGrievance: "Speak Grievance (Voice)",
      stopTranscribe: "Stop & Transcribe",
      listening: "Listening... Click to Finish",
      cardSubmitTitle: "Submit Grievance",
      cardSubmitDesc: "File a structured complaint with AI document analysis.",
      cardUploadTitle: "Upload Evidence",
      cardUploadDesc: "Verify deeds, agreements & FIRs via OCR readiness.",
      cardTrackTitle: "Track Status",
      cardTrackDesc: "Milestone progress timeline & guide action plans.",
      cardRightsTitle: "Legal Rights Guide",
      cardRightsDesc: "DLSA contacts, government schemes & helplines.",
      exploreDomainTitle: "Explore Legal Rights by Domain",
      askAnyTopic: "Ask any topic >",
      domainWomenTitle: "Women & Family Law",
      domainWomenDesc: "Maintenance, 498A, DV Act, Custody",
      domainLandTitle: "Land & Property",
      domainLandDesc: "Patta, Encroachment, Boundary disputes",
      domainConsumerTitle: "Consumer & RTI",
      domainConsumerDesc: "Product defect, RTI filing, Fair trade",
      domainLabourTitle: "Labour & Wage Rights",
      domainLabourDesc: "Unpaid dues, Gratuity, PF settlement",
      domainCyberTitle: "Emergency & Cyber Aid",
      domainCyberDesc: "Online fraud, 1930 Helpline, Harassment",
      activeGrievancesTitle: "My Active Grievances",
      activeGrievancesDesc: "Track your submitted complaints and legal guide notes.",
      viewAllGrievances: "View All Grievances →",
      loadingGrievances: "Loading your grievances...",
      noGrievancesTitle: "No active grievances found.",
      noGrievancesDesc: "Whenever you submit a grievance or request legal guide representation, your case details will appear here.",
      submitFirstGrievance: "Submit First Grievance"
    },
    submitComplaint: {
      headerTitle: "Citizen Grievance & Legal Filing",
      headerSubtitle: "Tamil Nadu Legal Services Authority • Official Grievance & Redressal Registry",
      aiGuidedTab: "AI-Guided Filing (5 Stages)",
      directFormTab: "Direct Form (Single Page)",
      stageOf: "Stage {step} of 5",
      stageNames: {
        tellAram: "Tell ARAM",
        aiUnderstanding: "AI Understanding",
        documents: "Documents",
        safetyGuides: "Safety & Guides",
        reviewSubmit: "Review & Submit"
      },
      stage1Title: "Tell ARAM what happened",
      stage1Desc: "Explain your problem naturally. You can type or speak in your language.",
      tellUsLabel: "Tell us what happened...",
      minChars: "Minimum 15 characters",
      tellUsPlaceholder: "Tell us what happened in your own words... (You can type or speak in Tamil, Tanglish, English, or Hindi)",
      speakProblem: "Speak your problem",
      listeningClickStop: "Listening... (Click to stop)",
      processingSpeech: "Processing speech...",
      languageLabel: "Language:",
      autoDetect: "✨ Auto-Detect",
      primaryBadge: "Primary",
      transcribedNarrative: "Transcribed Problem Narrative",
      speechBadge: "{lang} Speech",
      reviewEditTip: "Review & Edit: You can edit names, amounts, or dates directly in the text box above before clicking Analyse with ARAM.",
      yourDistrict: "Your District",
      districtHelp: "Your district helps ARAM connect you with the appropriate local assistance at the {district} District Legal Aid Desk.",
      clearText: "Clear text",
      analyzingLegal: "Analyzing Legal Context...",
      analyzeWithAram: "Analyse with ARAM →",
      stage2Title: "ARAM AI Case Assessment",
      listenSummary: "Listen Summary",
      stopAudio: "Stop Audio",
      formulatedTitle: "Formulated Problem Title",
      doneEditing: "Done Editing",
      editTitle: "Edit Title",
      priorityLabel: "Priority: {priority}",
      caseOverview: "Case Situation & Legal Overview",
      partiesIdentified: "Parties Identified",
      disputeClaimAmount: "Dispute Claim Amount",
      timelineDate: "Timeline / Incident Date",
      reliefQuestion: "What specific outcome or relief are you seeking?",
      reliefSubtitle: "Your requested resolution",
      reliefPlaceholder: "Example: I want formal mediation by TNSLSA to direct the landlord to refund my ₹50,000 security deposit with no illegal deductions.",
      speakBtn: "Speak",
      recordingBtn: "Recording...",
      applicableRemedies: "Applicable Statutory Remedies",
      backBtn: "Back",
      continueDocsBtn: "Continue to Documents & Evidence →",
      stage3Title: "Documents & Supporting Proof",
      stage3Desc: "Attach deeds, notices, receipts or agreements for automated readiness review.",
      ocrIntegrityReview: "Evidence Readiness & Document Integrity Review",
      continueSafetyBtn: "Continue to Safety & Assistance →",
      stage4Title: "Safety, Vulnerability & Legal Guide Representation",
      stage4Desc: "Configure sensitive protection rules and assign verified District Legal Services Authority representation.",
      continueReviewBtn: "Continue to Review & Submit →",
      stage5Title: "Review Grievance & Statutory Submission",
      stage5Desc: "Final verification before assigning case number and blockchain audit block logging.",
      declarationText: "I declare that the information provided is true to the best of my knowledge under legal aid provisions.",
      submitGrievanceBtn: "Submit Grievance to Legal Aid Desk →",
      submittingBtn: "Submitting to Legal Registry...",
      successTitle: "Grievance Successfully Filed!",
      successDesc: "Your grievance has been securely registered with Tamil Nadu Legal Services Authority and logged to the blockchain audit block.",
      officialRef: "Official Case Reference:",
      trackGrievanceBtn: "Track Grievance Status",
      returnDashboardBtn: "Return to Dashboard"
    },
    complaintHistory: {
      title: "My Grievance History",
      subtitle: "Track status, evidence verification, and legal guide notes for all submitted cases.",
      newGrievanceBtn: "New Grievance",
      searchPlaceholder: "Search complaints by title, ID, or description...",
      filterAll: "All Statuses",
      filterSubmitted: "Submitted",
      filterInProgress: "In Progress",
      filterResolved: "Resolved",
      noComplaintsTitle: "No grievances found",
      noComplaintsDesc: "You haven't filed any grievances yet or none match your filter.",
      fileFirstGrievance: "File First Grievance"
    },
    evidenceVault: {
      title: "Documents & Evidence Vault",
      subtitle: "Upload deeds, agreements, notices, and FIRs for instant OCR readiness validation and SHA-256 encrypted storage.",
      analyzerTitle: "OCR Document Legal Readiness Analyzer",
      analyzerSubtitle: "Verify registration numbers, survey boundaries, and statutory stamp seals before formal submission.",
      uploadBoxTitle: "Click to upload or drag and drop",
      uploadBoxSubtitle: "PDF, JPG, JPEG, PNG (Max 15MB)",
      verifyBtn: "Verify Document Readiness",
      verifyingBtn: "Analyzing Document OCR...",
      readinessScore: "Legal Readiness Score",
      detectedEntities: "Detected Legal Entities"
    },
    trackComplaint: {
      title: "Track Grievance Milestone Status",
      subtitle: "Enter your ARAM case reference ID to inspect official review progress, assigned guide, and next action plan.",
      inputPlaceholder: "Enter Case Reference ID (e.g., ARAM-2026-000001 or 1)...",
      trackBtn: "Track Case",
      trackingBtn: "Searching...",
      step1Title: "Grievance Filed",
      step1Desc: "Submitted securely to ARAM official registry",
      step2Title: "AI Triage & Categorization",
      step2Desc: "Applicable legal sections and checklists identified",
      step3Title: "Legal Guide Assignment",
      step3Desc: "Verified legal guide assigned for assistance",
      step4Title: "Authority Resolution",
      step4Desc: "Taluk / District legal action completed"
    },
    helpCenter: {
      title: "Legal Rights & Emergency Help Center",
      subtitle: "Certified statutory helplines, District Legal Services Authority (DLSA) access, and dispute guidelines.",
      nalsaTitle: "National Legal Services (NALSA)",
      nalsaDesc: "Free legal aid for eligible citizens under Legal Services Authorities Act",
      womenTitle: "Women Helpline",
      womenDesc: "24x7 support for domestic violence and emergency protection",
      cyberTitle: "National Cyber Crime Reporting",
      cyberDesc: "Financial fraud and cyber harassment immediate reporting",
      seniorTitle: "Senior Citizen Helpline",
      seniorDesc: "Elder abuse and maintenance dispute legal assistance",
      gatewayTitle: "Official ARAM Support Gateway",
      gatewayDesc: "For formal petition drafting inquiries or system support, email our dedicated gateway at"
    },
    auth: {
      layout: {
        mobileBadge: "TN Legal Copilot",
        mobileSubtitle: "Accessible Rights & Assistance Management System",
        mobileFooter: "End-to-End Encrypted • Govt. of TN Civic Aid"
      },
      banner: {
        govtTag: "Govt. of Tamil Nadu & Civic Aid",
        copilotDesc: "Accessible Rights & Assistance Management System • AI Legal Copilot",
        slide1Badge: "Grounded AI Triage",
        slide1Title: "Grounded Legal Guidance for Every Citizen",
        slide1Desc: "Instant statutory triage powered by certified Indian legal knowledge, penal codes, and acts in Tamil, Tanglish, Hindi, and English.",
        slide2Badge: "Institutional Security",
        slide2Title: "Encrypted & Direct Authority Grievance Filing",
        slide2Desc: "Connect seamlessly with local taluk offices, District Legal Services Authorities (DLSA), and verified advocates.",
        slide3Badge: "Multilingual Engine",
        slide3Title: "Voice-First Multilingual Accessibility",
        slide3Desc: "Speak your grievance naturally in your native language with voice-first assistance in Tamil, Hindi, and English.",
        trust1: "Zero Hallucination Grounded Legal Corpus",
        trust2: "Verified DLSA & Taluk Escalation",
        trust3: "Confidential 256-bit Encrypted Triage",
        officialSupport: "Official Support:",
        compliance: "Compliant with Indian IT Act & DPDP 2023",
        of: "of"
      },
      login: {
        backHome: "Back to Home",
        portalBadge: "Unified Civic Portal",
        title: "Sign In",
        subtitle: "Access your legal assistance records, grievances, and guidance cases.",
        emailLabel: "Email Address",
        emailPlaceholder: "name@example.com",
        passwordLabel: "Password",
        passwordPlaceholder: "••••••••••••",
        forgotPassword: "Forgot Password?",
        rememberMe: "Remember this device for 30 days",
        signInBtn: "Sign In to Account",
        signingIn: "Signing in...",
        orContinueWith: "or continue with",
        googleSignIn: "Sign in with Google",
        quickDemo: "Quick Demo Credentials",
        hideDemo: "Hide Demo Accounts",
        roleCitizen: "Citizen",
        roleAdmin: "Salem Admin",
        roleGuide: "Salem Guide",
        roleSuperAdmin: "Super Admin",
        demoHint: "Any district works: <district>.admin@gmail.com / Admin@123 & <district>.guide1@gmail.com / Admin@123",
        noAccount: "Don't have an account yet?",
        createAccount: "Create Free Citizen Profile →",
        emailPasswordRequired: "Please enter both your email and password.",
        loginSuccess: "Welcome back to ARAM AI Legal Aid!",
        invalidCredentials: "Invalid email or password. Please verify your credentials."
      },
      forgotPassword: {
        backSignIn: "Back to Sign In",
        badge: "Account Security Recovery",
        title: "Reset Password",
        subtitle: "Enter your registered email address or 10-digit mobile number to receive a secure 6-digit OTP code.",
        inputLabel: "Email Address or Mobile Number",
        inputPlaceholder: "name@example.com or 9876543210",
        sendOtp: "Send Verification OTP",
        sendingOtp: "Dispatching OTP...",
        accountNotFound: "Account Not Found",
        verificationError: "Verification Error",
        createNewAccount: "Create New Account"
      },
      register: {
        backSignIn: "Back to Sign In",
        badge: "Official Civic Registration",
        title: "Create Citizen Profile",
        subtitle: "Join the Tamil Nadu Legal Aid network for AI triage, case tracking, and legal guide escalation.",
        fullName: "Full Name",
        fullNamePlaceholder: "e.g., Anbarasan K",
        email: "Email Address",
        emailPlaceholder: "name@example.com",
        mobile: "Mobile Number",
        mobilePlaceholder: "9876543210",
        district: "District / மாவட்டம்",
        password: "Password",
        confirmPassword: "Confirm Password",
        terms: "I accept the Terms of Service & Civic Data Privacy Guidelines",
        submitBtn: "Create Free Citizen Profile",
        submitting: "Creating Profile...",
        alreadyAccount: "Already have an account?",
        signInLink: "Sign In →"
      },
      otp: {
        backSignIn: "Back to Sign In",
        badge: "Two-Factor Verification",
        title: "Verify OTP Code",
        subtitle: "Enter the 6-digit verification code dispatched to your mobile and email.",
        verifyBtn: "Verify Code & Proceed",
        verifying: "Verifying Code...",
        resendIn: "Resend code in {seconds}s",
        resendBtn: "Resend Verification Code",
        otpRequired: "Please enter the 6-digit OTP code."
      },
      google: {
        title: "Sign in with Google",
        subtitle: "Choose an account to continue to ARAM",
        badge: "Verified Institutional Access",
        desc: "Choose an active seeded credential or provide custom Google OAuth credentials.",
        verifiedProfiles: "Verified Profiles",
        customAccount: "Enter Custom Google Email",
        useAnother: "Use another Google account",
        emailLabel: "Google Email Address",
        emailPlaceholder: "yourname@gmail.com",
        nameLabel: "Full Name (Optional)",
        namePlaceholder: "e.g., Anandha Krishnan",
        continueBtn: "Continue with this Google Account",
        verifyingBtn: "Verifying Google Account...",
        securityNote: "Grounded & encrypted under Indian IT Act & DPDP 2023",
        continueAs: "Continue as {name}",
        cancel: "Cancel",
        citizenBadge: "Verified Citizen",
        guideBadge: "Legal Guide",
        adminBadge: "Regional Admin",
        superAdminBadge: "State Administrator"
      }
    }
  },
  "ta-IN": {
    nav: {
      home: "முகப்பு",
      about: "அறிமுகம்",
      services: "சேவைகள்",
      howItWorks: "அறம் செயல்படும் விதம்",
      trackCase: "வழக்கைக் கண்காணிக்க",
      trackGrievance: "புகாரைக் கண்காணிக்க",
      contact: "தொடர்புக்கு",
      signIn: "உள்நுழைக",
      dashboard: "டாஷ்போர்டு",
      askAi: "அறம் AI-யிடம் கேட்க"
    },
    hero: {
      badge: "குடிமக்கள் சட்ட உதவி & குறைதீர்க்கும் தளம்",
      eyebrow: "ஒவ்வொரு குடிமகனுக்கும் சமமான நீதி",
      title1: "உங்கள் உரிமை. எங்கள் ஆதரவு.",
      title2: "நீதியான எதிர்காலம்.",
      subtitle: "சட்டத் தகவல்களைப் புரிந்துகொள்ளவும், சரியான அதிகாரிகளைக் கண்டறியவும், ஆதாரங்களை ஒழுங்கமைக்கவும், சான்றளிக்கப்பட்ட சட்ட வழிகாட்டிகளுடன் இணையவும் அறம் குடிமக்களுக்கு உதவுகிறது — தமிழ், ஆங்கிலம் மற்றும் இந்தியில்.",
      askAi: "அறம் AI-யிடம் கேட்க",
      fileGrievance: "புகார் பதிவு செய்க",
      trackCase: "வழக்கைக் கண்காணிக்க",
      speakProblem: "குரலில் கூற",
      listening: "கேட்கிறது... முடிக்க கிளிக் செய்யவும்",
      uploadDoc: "ஆவணம் பதிவேற்ற",
      connectGuide: "சட்ட வழிகாட்டியை அணுக",
      noLegalFees: "சட்டக் கட்டணம் இல்லை",
      piiPrivacy: "கடுமையான தனியுரிமை பாதுகாப்பு",
      dlsaAligned: "தமிழ்நாடு DLSA அங்கீகாரம்"
    },
    trustStrip: {
      multilingual: "மும்மொழி சட்ட உதவி",
      multilingualDesc: "தமிழ் • ஆங்கிலம் • இந்தி",
      verified: "உறுதிப்படுத்தப்பட்ட சட்ட விதிகள்",
      verifiedDesc: "சான்றளிக்கப்பட்ட இந்திய சட்டப் பிரிவுகள்",
      humanSupport: "மனித வழிகாட்டி & DLSA ஆதரவு",
      humanSupportDesc: "அங்கீகரிக்கப்பட்ட சட்டப் பிரதிநிதித்துவம்",
      districtAware: "38 மாவட்ட வழிகாட்டல்",
      districtAwareDesc: "தமிழ்நாட்டின் அனைத்து மாவட்டங்களுக்கும்",
      liveRegistry: "மாநில அளவிலான நேரடி குடிமக்கள் பதிவேடு",
      platformIndicators: "மாநில அளவிலான சட்ட உதவி புள்ளிவிவரங்கள்",
      verifiedRealTime: "சரிபார்க்கப்பட்ட நேரடி எண்ணிக்கைகள்",
      tnGovInitiative: "தமிழ்நாடு அரசு • குடிமக்கள் சட்ட உதவி முயற்சி",
      totalComplaints: "மொத்த புகார்கள்",
      acrossDistricts: "38 மாவட்டங்களில்",
      activeInReview: "பரிசீலனையில் உள்ளவை",
      underDlsa: "DLSA சட்ட நடைமுறையில்",
      resolvedCases: "தீர்க்கப்பட்ட வழக்குகள்",
      citizensHelped: "பயனடைந்த குடிமக்கள்",
      legalGuides: "சட்ட வழிகாட்டிகள்",
      acrossTn: "தமிழ்நாடு முழுவதும்",
      quote: "“நீதிக்கான சம உரிமை மக்களாட்சியை பலப்படுத்துகிறது.”",
      quoteAuthor: "— தேசிய சட்ட சேவைகள் ஆணையம் (NALSA)"
    },
    waysToGetHelp: {
      tag: "உதவி பெறும் வழிகள்",
      title: "உங்களுக்கு விருப்பமான வழியைத் தேர்ந்தெடுக்கவும்",
      subtitle: "ஒவ்வொரு குடிமகனுக்கும் ஏற்ற வகையில் எளிமையான தொடர்பு வழிகள்.",
      civicAssistance: "இலவச குடிமக்கள் சட்ட உதவி • எவ்வித கட்டணமும் இல்லை",
      speakTitle: "குரல்வழி பேச",
      speakSubtitle: "நேரடி குரல் உதவி",
      speakDesc: "உங்கள் பிரச்சினையை தமிழ், ஆங்கிலம் அல்லது இந்தியில் இயல்பாகப் பேசி விளக்குங்கள்.",
      speakAction: "பேசித் தொடங்க",
      speakListening: "கேட்கிறது...",
      speakBadge: "தமிழ் • இந்தி • ஆங்கிலம்",
      typeTitle: "எழுதி உரையாட",
      typeSubtitle: "AI உடனடி அரட்டை",
      typeDesc: "உங்கள் வார்த்தைகளில் விவரங்களை எழுதவும். உடனடி சட்ட ஆய்வு மற்றும் வழிகாட்டல் பெறவும்.",
      typeAction: "AI உடன் பேச",
      typeBadge: "24/7 சேவை",
      uploadTitle: "ஆவணம் பதிவேற்ற",
      uploadSubtitle: "சான்றுகள் & பத்திரங்கள்",
      uploadDesc: "பத்திரங்கள், நோட்டீஸ்கள், மனுக்கள் அல்லது ரசீதுகளைப் பதிவேற்றி ஆய்வு செய்யுங்கள்.",
      uploadAction: "ஆவணத்தை ஆய்வு செய்ய",
      uploadBadge: "OCR சரிபார்ப்பு தயார்",
      connectTitle: "நேரடி வழிகாட்டி",
      connectSubtitle: "சட்ட தன்னார்வலர்கள்",
      connectDesc: "நேரடி மனித உதவி தேவைப்படும் போது சான்றளிக்கப்பட்ட மாவட்ட சட்ட வழிகாட்டிகளுடன் இணையுங்கள்.",
      connectAction: "வழிகாட்டியை அணுக",
      connectBadge: "DLSA அங்கீகாரம்"
    },
    aiHuman: {
      tag: "AI மற்றும் மனித ஒருங்கிணைப்பு",
      title: "சாத்தியமான இடங்களில் AI. தேவையான போது சட்ட வழிகாட்டி.",
      subtitle: "விரைவான AI சட்டப் பகுப்பாய்வும், அனுபவமிக்க சட்ட வழிகாட்டிகளின் நம்பிக்கையான ஆதரவும்.",
      desc1: "அறம் AI உடனடியாக உங்கள் வழக்கின் விவரங்களை ஒழுங்கமைத்து, பொருத்தமான சட்டப் பிரிவுகளைக் கண்டறிந்து, தேவையான ஆவணங்களை வகைப்படுத்துகிறது.",
      desc2: "மனு வரைவு, சட்டப்பூர்வ மனுத் தாக்கல் அல்லது DLSA பிரதிநிதித்துவம் தேவைப்படும் போது, அங்கீகரிக்கப்பட்ட சட்ட வழிகாட்டிகள் நேரடியாக உங்களுடன் இணைகிறார்கள்.",
      bullet1: "24x7 உடனடி முதற்கட்ட சட்ட ஆய்வு மற்றும் உரிமை விளக்கம்",
      bullet2: "தானியங்கி நிராகரிப்பு இல்லை — சிக்கலான வழக்குகளுக்கு மனித வழிகாட்டி ஆய்வு",
      bullet3: "வட்டார மற்றும் மாவட்ட சட்டப் பணிகள் ஆணைக்குழுவுடன் (DLSA) நேரடி ஒருங்கிணைப்பு",
      aiTitle: "AI சட்ட உதவி",
      aiSubtitle: "24/7 உடனடி முதற்கட்ட வழிகாட்டல்",
      humanTitle: "மனித வழிகாட்டி ஆதரவு",
      humanSubtitle: "அங்கீகரிக்கப்பட்ட DLSA & சட்ட வழிகாட்டிகள்",
      startAi: "AI சட்ட ஆய்வைத் தொடங்குக",
      requestGuide: "சட்ட வழிகாட்டியை அணுகுக"
    },
    immediateHelp: {
      tag: "அவசர மற்றும் சட்ட உதவி எண்கள்",
      title: "உடனடி அவசர உதவி தேவையா?",
      subtitle: "அவசர விபத்து, மகளிர் பாதுகாப்பு, இணையக் குற்றங்கள் மற்றும் இலவச சட்ட உதவிக்கான அதிகாரப்பூர்வ அரசு எண்கள்.",
      emergency: "அவசரக் காவல் & மருத்துவ உதவி",
      emergencySub: "காவல்துறை, தீயணைப்பு & ஆம்புலன்ஸ் (24x7)",
      women: "மகளிர் உதவி எண்",
      womenSub: "பாதுகாப்பு & குடும்ப வன்முறை தடுப்பு (24x7)",
      cyber: "இணையக் குற்றப் பிரிவு",
      cyberSub: "தேசிய நிதி மோசடி தடுப்பு உதவி எண்",
      legalAid: "இலவச சட்ட உதவி (NALSA)",
      legalAidSub: "இலவச சட்ட உதவி & DLSA மையம்"
    },
    howItWorks: {
      tag: "குடிமக்கள் சட்டப் பயணம்",
      title: "அறம் எவ்வாறு உதவுகிறது?",
      subtitle: "முதல் சட்டக் கேள்வியிலிருந்து சான்றளிக்கப்பட்ட சட்டப் பிரதிநிதித்துவம் வரை — எளிய, வெளிப்படையான, உறுதியான சட்டப் பாதை.",
      notice: "அறம் என்பது பொதுமக்களுக்கான நிர்வாக மற்றும் சட்ட விழிப்புணர்வு அணுகல் தளம்; இது நீதிமன்றம் அல்ல. அனைத்து அதிகாரப்பூர்வ சட்ட மனுக்களும் அங்கீகரிக்கப்பட்ட சட்ட வழிகாட்டிகள் மூலமாகவே முன்னெடுக்கப்படும்.",
      phase: "நிலை",
      step1Title: "அறத்திடம் பகிருங்கள்",
      step1Subtitle: "எளிய உள்ளீடு",
      step1Desc: "உங்கள் பிரச்சினையை தமிழ், ஆங்கிலம் அல்லது இந்தியில் இயல்பாகப் பேசுங்கள் அல்லது எழுதுங்கள்.",
      step2Title: "வழக்கைப் புரிந்துகொள்ளுங்கள்",
      step2Subtitle: "சட்ட ஆய்வு",
      step2Desc: "உரிய சட்டப் பிரிவுகள், குற்றவியல் விதிகள் மற்றும் முக்கிய அம்சங்களை அறம் பகுப்பாய்வு செய்கிறது.",
      step3Title: "சான்றளிக்கப்பட்ட வழிகாட்டல்",
      step3Subtitle: "ஆதாரங்கள் & விதிகள்",
      step3Desc: "அங்கீகரிக்கப்பட்ட சட்ட விதிகள், துறைமுக பகிர்வு மற்றும் சான்றுகள் சரிபார்ப்பு பட்டியல் உருவாக்கப்படுகிறது.",
      step4Title: "மனித வழிகாட்டி ஆதரவு",
      step4Subtitle: "DLSA & சட்ட வழிகாட்டிகள்",
      step4Desc: "உங்கள் வழக்கு மாவட்ட சட்டப் பணிகள் ஆணைக்குழு மற்றும் அங்கீகரிக்கப்பட்ட சட்ட வழிகாட்டிகளுக்குப் பகிரப்படுகிறது.",
      step5Title: "வழக்கைக் கண்காணிக்கவும்",
      step5Subtitle: "முழு வெளிப்படைத்தன்மை",
      step5Desc: "வழக்கின் நேரடி நிலையை அறிந்து கொள்ளலாம், WhatsApp/SMS வழியாக விவரங்கள் மற்றும் அதிகாரப்பூர்வ PDF பெறலாம்."
    },
    features: {
      tag: "நீதிக்காக உருவாக்கப்பட்டது",
      title: "அறம் AI உங்கள் சட்ட உரிமைகளை எவ்வாறு பாதுகாக்கிறது",
      subtitle: "சான்றளிக்கப்பட்ட இந்திய சட்டப் பிரிவுகளின் அடிப்படையில் துல்லியமான, பொய்யற்ற சட்ட வழிகாட்டல்.",
      f1Title: "11-அடுக்கு சட்ட பகுப்பாய்வு",
      f1Desc: "ஒவ்வொரு கேள்விக்கும் உரிய சட்டப் பிரிவு, அடுத்த கட்ட நடைமுறைகள், ஆவணப் பட்டியல் மற்றும் DLSA வழிகாட்டல் வழங்கப்படுகிறது.",
      f2Title: "பன்மொழி குரல் உதவியாளர்",
      f2Desc: "தமிழ், இந்தி மற்றும் ஆங்கிலத்தில் நேரடியாகப் பேசி உடனடி சட்ட வழிகாட்டல் பெறலாம்.",
      f3Title: "OCR ஆவண சரிபார்ப்பு",
      f3Desc: "பத்திரம், பாகப்பிரிவினை மற்றும் நோட்டீஸ் போன்ற ஆவணங்களின் தயார்நிலை மதிப்பீடு.",
      f4Title: "சான்றளிக்கப்பட்ட சட்ட வழிகாட்டிகள்",
      f4Desc: "AI மதிப்பீட்டிலிருந்து நேரடி உள்ளூர் சட்ட வழிகாட்டிகள் மற்றும் மாவட்ட சட்டப் பணிகள் ஆணைக்குழுவுக்கு (DLSA) விரைவுப் பகிர்வு."
    },
    about: {
      tag: "எங்கள் நோக்கம்",
      title: "அனைத்து குடிமக்களுக்கும் சட்ட உரிமைகளை எளிதாக்குதல்",
      desc1: "மொழி, இருப்பிடம் அல்லது பொருளாதார நிலை நீதிக்கான தடையாக இருக்கக்கூடாது என்ற உயரிய நோக்கில் அறம் உருவாக்கப்பட்டது.",
      desc2: "சட்ட அறிவையும், சான்றளிக்கப்பட்ட வழிகாட்டிகளையும் நேரடியாக குடிமக்களிடம் கொண்டுசேர்ப்பதே அறத்தின் முதன்மைப் பணி.",
      commitmentsTitle: "அறத்தின் அடிப்படைக் கொள்கைகள்",
      c1: "துல்லியமான தகவல்: அனைத்து சட்ட ஆலோசனைகளும் சான்றளிக்கப்பட்ட சட்ட விதிகளின்படி சரிபார்க்கப்படுகிறது.",
      c2: "தனிநபர் பாதுகாப்பு: ஆதார் உள்ளிட்ட தனிப்பட்ட விவரங்களின் தானியங்கி பாதுகாப்பு.",
      c3: "அதிகாரப்பூர்வ தொடர்பு: ouraramsupport@gmail.com மூலம் முறையான மின்னஞ்சல் அறிவிப்புகள்."
    },
    whoCanUse: {
      tag: "பயனாளர் சுற்றுச்சூழல்",
      title: "அறம் தளத்தை யார் பயன்படுத்தலாம்?",
      subtitle: "சட்ட விழிப்புணர்வு மற்றும் குறைதீர்க்கும் அமைப்பில் உள்ள அனைத்து தரப்பினரையும் இணைக்க உருவாக்கப்பட்டது.",
      tagPublic: "பொதுமக்கள் அணுகல்",
      tagAssistance: "வழக்கு உதவி",
      tagAuthority: "அதிகாரிகள் ஆய்வு",
      tagGovernance: "மேலாண்மை",
      u1Title: "குடிமக்கள்",
      u1Desc: "உங்கள் தாய்மொழியில் புகார்களைப் பேசி/எழுதி, சட்ட உரிமைகளைப் புரிந்து கொண்டு, வழக்கின் முன்னேற்றத்தைக் கண்காணிக்கலாம்.",
      u2Title: "சட்ட வழிகாட்டிகள் & தன்னார்வலர்கள்",
      u2Desc: "AI ஆய்வை மதிப்பாய்வு செய்து, மனு வரைவுக்கு உதவி, களத்தில் சட்ட வழிகாட்டல் வழங்கும் அங்கீகரிக்கப்பட்ட சட்ட தன்னார்வலர்கள்.",
      u3Title: "அரசு அலுவலர்கள்",
      u3Desc: "சரிபார்க்கப்பட்ட ஆதாரங்களுடன் முறைப்படுத்தப்பட்ட மனுக்களைப் பெற்று சட்டப்பூர்வ தீர்வு காணும் மாவட்ட மற்றும் DLSA அதிகாரிகள்.",
      u4Title: "தள நிர்வாகிகள்",
      u4Desc: "மாவட்ட அளவிலான புகார் தீர்வு, தணிக்கை பதிவுகள் மற்றும் சேவைத் தரத்தை மேற்பார்வையிடும் தலைமை நிர்வாகிகள்."
    },
    cta: {
      title: "உங்கள் சட்ட உரிமைகளைத் தெரிந்துகொள்ளத் தயாரா?",
      subtitle: "உங்கள் முதல் சட்டக் கேள்வியைக் கேளுங்கள், ஆவணங்களைச் சரிபாருங்கள், அல்லது சட்ட வழிகாட்டியை இன்றே அணுகுங்கள்.",
      button: "இலவச சட்ட வழிகாட்டலைத் தொடங்குக",
      tag: "சட்டத் தீர்வைத் தொடங்குங்கள்",
      heading: "எங்கு தொடங்குவது என்று தெரியவில்லையா?",
      desc: "நடந்ததை அறத்திடம் பகிருங்கள். உங்கள் உரிமைகளைப் புரிந்துகொள்ளவும், ஆவணங்களைத் தயார் செய்யவும், அடுத்த கட்ட நடவடிக்கையைக் கண்டறியவும் நாங்கள் உதவுகிறோம்.",
      askAi: "அறம் AI-யிடம் கேட்க",
      fileGrievance: "புகாரைப் பதிவு செய்ய",
      footerNote: "இலவச மக்கள் சேவை • முழுமையான ரகசியம் • இந்திய சட்ட விதிகளின்படி"
    },
    immediateHelp: {
      tag: "அவசர & சட்டப்பூர்வ ஆதரவு",
      title: "உடனடி உதவி தேவையா?",
      subtitle: "அவசர நிகழ்வுகள், மகளிர் பாதுகாப்பு, இணைய நிதி மோசடி மற்றும் இலவச சட்ட உதவிக்கான அதிகாரப்பூர்வ அரசு உதவி எண்கள்.",
      emergency: "அவசர கால சேவைகள்",
      emergencySub: "காவல்துறை, தீயணைப்பு & ஆம்புலன்ஸ் (24x7)",
      badgeEmergency: "தேசிய அவசர எண்",
      women: "மகளிர் உதவி எண்",
      womenSub: "பாதுகாப்பு & குடும்ப வன்முறை உதவி (24x7)",
      badgeWomen: "மகளிர் பாதுகாப்பு",
      cyber: "சைபர் குற்ற உதவி எண்",
      cyberSub: "தேசிய நிதி மோசடி தடுப்புப் பிரிவு",
      badgeCyber: "இணைய நிதி மோசடி",
      legalAid: "NALSA சட்ட உதவி",
      legalAidSub: "இலவச சட்ட உதவி & மாவட்ட தாலுகா சேவைகள்",
      badgeLegalAid: "இலவச சட்ட உதவி",
      tapToCall: "அழைக்க தட்டவும் {number}"
    },
    civicFeatures: {
      petitionTitle: "சமர்ப்பிக்கத் தயாரான அதிகாரப்பூர்வ மனு",
      petitionSub: "தொடர்புடைய துறை அதிகாரிக்கு சமர்ப்பிக்கும் வகையில் முறைப்படுத்தப்பட்ட சட்டப்பூர்வ விண்ணப்பம்.",
      btnGeneratePetition: "அதிகாரப்பூர்வ மனு நகலை உருவாக்குதல்",
      btnPrintPetition: "மனுவை அச்சிட (Print)",
      btnCopyPetition: "மனு உரையை நகலெடு",
      langTamil: "தமிழில் மனு நகல்",
      langEnglish: "ஆங்கிலத்தில் மனு நகல்",
      petitionFrom: "அனுப்புநர் (மனுதாரர்):",
      petitionTo: "பெறுநர் (துறை அதிகாரி):",
      petitionSubject: "பொருள்:",
      petitionFacts: "புகாரின் விவரங்கள் & உண்மைகள்:",
      petitionProvisions: "பொருந்தக்கூடிய சட்டப் பிரிவுகள்:",
      petitionPrayer: "கோரிக்கை / நிவாரணம்:",
      petitionVerification: "மேற்கூறிய விவரங்கள் அனைத்தும் எனது அறிவிற்கும் நம்பிக்கைக்கும் எட்டியவரை முற்றிலும் உண்மை என உளமார உறுதிப்படுத்துகிறேன்.",
      petitionSignature: "மனுதாரரின் கையொப்பம் / கைரேகை",
      
      sec12Title: "NALSA பிரிவு 12 இலவச சட்ட உதவி தகுதி",
      sec12Sub: "சட்ட சேவைகள் அதிகார சட்டம் 1987-ன் படி 100% இலவச அரசு வழக்கறிஞர் உதவிக்கு நீங்கள் தகுதியானவரா என அறிக.",
      btnCheckSec12: "இலவச சட்ட உதவி தகுதியைச் சரிபார்க்கவும்",
      sec12Q1: "நீங்கள் பெண் அல்லது 18 வயதுக்குட்பட்டவரா?",
      sec12Q2: "நீங்கள் பட்டியல் சாதியினர் (SC) அல்லது பழங்குடியினரா (ST)?",
      sec12Q3: "நீங்கள் மாற்றுத்திறனாளியா அல்லது பேரிடர்/வன்முறையால் பாதிக்கப்பட்டவரா?",
      sec12Q4: "உங்கள் குடும்ப ஆண்டு வருமானம் ₹3,00,000-க்குள் உள்ளதா (தமிழ்நாடு வரம்பு)?",
      sec12Eligible: "100% இலவச சட்ட உதவிக்கு தகுதியானவர்",
      sec12EligibleDesc: "அரசு செலவில் DLSA மூலம் இலவச நீதிமன்ற வழக்கறிஞர் பிரதிநிதித்துவத்தைப் பெற நீங்கள் சட்டப்பூர்வமாகத் தகுதியுடையவர்.",
      sec12NotEligible: "பொது சட்ட வழிகாட்டல் பயன்முறை",
      sec12NotEligibleDesc: "நீதிமன்ற வழக்கறிஞருக்கு பிரிவு 12 தகுதி பொருந்தாவிட்டாலும், அறம் AI மற்றும் சட்ட வழிகாட்டி சேவைகள் என்றும் இலவசம்.",
      
      ratingTitle: "குடிமக்கள் திருப்தி & தீர்வு மதிப்பாய்வு",
      ratingSub: "உங்கள் புகாருக்கு வழங்கப்பட்ட சட்ட உதவி மற்றும் தீர்வு குறித்த அதிகாரப்பூர்வ மதிப்பாய்வு.",
      rateExperience: "உங்கள் புகாரின் தீர்வை எவ்வாறு மதிப்பிடுவீர்கள்?",
      wasHelpful: "சட்ட வழிகாட்டியின் வழிகாட்டல் பயனுள்ளதாக இருந்ததா?",
      yesHelpful: "ஆம், மிகவும் பயனுள்ளது",
      noHelpful: "மேம்படுத்தப்பட வேண்டும்",
      feedbackPlaceholder: "வழங்கப்பட்ட தீர்வு குறித்த உங்கள் கருத்துகளைப் பதிவிடவும்...",
      btnSubmitRating: "தீர்வை உறுதிசெய்து மதிப்பீட்டைச் சமர்ப்பிக்க",
      lowRatingAlert: "இந்த தீர்வில் திருப்தி இல்லையா?",
      lowRatingDesc: "உங்கள் குறை முறையாகத் தீர்க்கப்படவில்லை எனில், மாவட்ட நிர்வாக ஆய்வுக்கு மேல்முறையீடு செய்து வழக்கை மீண்டும் தொடங்கும் உரிமை உங்களுக்கு உண்டு.",
      btnAppealReopen: "அதிகாரப்பூர்வ மேல்முறையீடு / வழக்கை மீண்டும் திறக்க",
      alreadyRated: "நீங்கள் இந்தத் தீர்வை மதிப்பிட்டுள்ளீர்கள் ({stars}/5 நட்சத்திரங்கள்)",
      
      appointmentTitle: "10 நிமிட வழிகாட்டுதல் அழைப்பைக் கோருக",
      appointmentSub: "ஒதுக்கப்பட்ட சட்ட வழிகாட்டியுடன் தொலைபேசி அல்லது குரல்வழி ஆலோசனையைத் திட்டமிடுங்கள்.",
      btnRequestCall: "வழிகாட்டுதல் அழைப்பைக் கோருக",
      selectMode: "ஆலோசனை முறை",
      modePhone: "தொலைபேசி அழைப்பு (மொபைல்)",
      modeApp: "செயலி வழி குரல் ஆலோசனை",
      modeWa: "வாட்ஸ்அப் குரல் / உரை வழிகாட்டல்",
      selectSlot: "விருப்பமான நேர இடைவெளி",
      slotMorning: "காலை (10:00 AM – 01:00 PM)",
      slotAfternoon: "பிற்பகல் (02:00 PM – 05:00 PM)",
      slotEvening: "மாலை (05:00 PM – 08:00 PM)",
      appointmentNote: "நீங்கள் விவாதிக்க விரும்பும் முக்கியக் கேள்வி",
      btnSubmitAppointment: "அழைப்பு கோரிக்கையை உறுதிசெய்க",
      appointmentActive: "வழிகாட்டுதல் அழைப்பு கோரப்பட்டுள்ளது",
      
      lokAdalatTitle: "லோக் அதாலத் சமரசத்திற்குத் தகுதியானது",
      lokAdalatDesc: "இப்பிரச்சனையை தேசிய / தாலுகா லோக் அதாலத் மூலம் நீதிமன்றக் கட்டணமின்றி சுமுகமாகத் தீர்க்க முடியும். இது சிவில் நீதிமன்றத் தீர்ப்புக்கு இணையான அந்தஸ்து கொண்டது.",
      
      atrTitle: "அதிகாரப்பூர்வ நடவடிக்கை அறிக்கை (ATR)",
      atrSub: "ஒதுக்கப்பட்ட சட்ட வழிகாட்டி / மாவட்ட அதிகாரியால் வழங்கப்பட்ட அதிகாரப்பூர்வ தீர்வு குறிப்பு.",
      atrVerified: "சட்டப்பூர்வ சரிபார்ப்பு நிறைவடைந்தது"
    },
    sidebar: {
      portalTitle: "சட்ட உதவி தளம்",
      dashboard: "டாஷ்போர்டு",
      askAi: "அறம் AI-யிடம் கேளுங்கள்",
      submitGrievance: "குறை சமர்ப்பிக்க",
      myGrievances: "எனது புகார்கள்",
      documentsEvidence: "ஆவணங்கள் & ஆதாரங்கள்",
      trackStatus: "நிலையைக் கண்காணிக்க",
      supportSettings: "ஆதரவு & அமைப்புகள்",
      notifications: "அறிவிப்புகள்",
      helpRights: "உதவி & உரிமைகள் வழிகாட்டி",
      profileSettings: "சுயவிவரம் & அமைப்புகள்",
      signOut: "வெளியேறு"
    },
    topbar: {
      searchCitizen: "அறம் AI-யிடம் சட்டக் கேள்விகளைக் கேளுங்கள் (எ.கா. நில உரிமை, RTI, 498A)...",
      searchAdmin: "38 மாவட்ட புகார்களையும் தேட (எண், குடிமகன், தலைப்பு)...",
      searchGuide: "ஒதுக்கப்பட்ட வழக்குகள் அல்லது சட்ட தலைப்புகளைத் தேட...",
      lightMode: "வெளிச்ச பயன்முறைக்கு மாறுக",
      darkMode: "இரவு பயன்முறைக்கு மாறுக",
      notifications: "அறிவிப்புகள்"
    },
    citizenDashboard: {
      portalBadge: "தமிழ்நாடு பொது சட்ட உதவி & குறைதீர்க்கும் தளம்",
      heroGreeting: "வணக்கம், {name}. அறம் இன்று உங்களுக்கு எவ்வாறு உதவ முடியும்?",
      heroDescription: "தமிழ், ஆங்கிலம் அல்லது இந்தியில் உங்கள் சட்டச் சிக்கல் அல்லது புகாரை விளக்கி, உடனடி சரிபார்க்கப்பட்ட வழிகாட்டுதல், தேவையான ஆவணப் பட்டியல் மற்றும் சட்ட வழிகாட்டி உதவியைப் பெறுங்கள்.",
      askLegalAssistant: "அறம் சட்ட உதவியாளரிடம் கேளுங்கள்",
      speakGrievance: "குறையைப் பேசுங்கள் (குரல்வழி)",
      stopTranscribe: "நிறுத்தி உரை பெறுக",
      listening: "கேட்கிறது... முடிக்க கிளிக் செய்யவும்",
      cardSubmitTitle: "குறை சமர்ப்பிக்க",
      cardSubmitDesc: "AI ஆவண பகுப்பாய்வுடன் முறையான புகாரைப் பதிவு செய்யுங்கள்.",
      cardUploadTitle: "ஆதாரம் பதிவேற்ற",
      cardUploadDesc: "பத்திரங்கள், ஒப்பந்தங்கள் & FIR நகல்களை OCR மூலம் சரிபார்க்கவும்.",
      cardTrackTitle: "நிலையைக் கண்காணிக்க",
      cardTrackDesc: "வழக்கின் முன்னேற்ற காலவரிசை & வழிகாட்டி செயல் திட்டங்கள்.",
      cardRightsTitle: "சட்ட உரிமைகள் வழிகாட்டி",
      cardRightsDesc: "DLSA தொடர்புகள், அரசு திட்டங்கள் & உதவி எண்கள்.",
      exploreDomainTitle: "துறை வாரியாக சட்ட உரிமைகளை அறிக",
      askAnyTopic: "எந்த தலைப்பையும் கேட்கலாம் >",
      domainWomenTitle: "பெண்கள் & குடும்ப சட்டம்",
      domainWomenDesc: "ஜீவனாம்சம், 498A, குடும்ப வன்முறை சட்டம், குழந்தை பராமரிப்பு",
      domainLandTitle: "நிலம் & சொத்துரிமை",
      domainLandDesc: "பட்டா, ஆக்கிரமிப்பு, எல்லை தகராறுகள்",
      domainConsumerTitle: "நுகர்வோர் & தகவல் அறியும் உரிமை (RTI)",
      domainConsumerDesc: "குறைபாடுள்ள பொருள், RTI மனு, நியாயமான வணிகம்",
      domainLabourTitle: "தொழிலாளர் & ஊதிய உரிமைகள்",
      domainLabourDesc: "நிலுவை ஊதியம், பணிக்கொடை, PF தீர்வு",
      domainCyberTitle: "அவசர உதவி & சைபர் குற்றங்கள்",
      domainCyberDesc: "ஆன்லைன் மோசடி, 1930 உதவி எண், தொல்லைகள்",
      activeGrievancesTitle: "எனது தற்போதைய புகார்கள்",
      activeGrievancesDesc: "உங்கள் புகார்கள் மற்றும் வழிகாட்டி குறிப்புகளைக் கண்காணிக்கவும்.",
      viewAllGrievances: "அனைத்து புகார்களையும் பார்க்க →",
      loadingGrievances: "உங்கள் புகார்கள் ஏற்றப்படுகின்றன...",
      noGrievancesTitle: "செயலில் உள்ள புகார்கள் எதுவும் இல்லை.",
      noGrievancesDesc: "நீங்கள் புகாரைப் பதிவு செய்யும்போதோ அல்லது வழிகாட்டியை கோரும்போதோ விவரங்கள் இங்கே தோன்றும்.",
      submitFirstGrievance: "முதல் புகாரைப் பதிவு செய்க"
    },
    submitComplaint: {
      headerTitle: "குடிமக்கள் குறை & சட்டப் பதிவு",
      headerSubtitle: "தமிழ்நாடு சட்டப் பணிகள் ஆணைக்குழு • அதிகாரப்பூர்வ குறைதீர்ப்புப் பதிவகம்",
      aiGuidedTab: "AI வழிகாட்டுதல் பதிவு (5 நிலைகள்)",
      directFormTab: "நேரடி படிவம் (ஒற்றைப் பக்கம்)",
      stageOf: "நிலை {step} / 5",
      stageNames: {
        tellAram: "விளக்கம்",
        aiUnderstanding: "AI பகுப்பாய்வு",
        documents: "ஆவணங்கள்",
        safetyGuides: "பாதுகாப்பு & வழிகாட்டி",
        reviewSubmit: "சரிபார்த்து சமர்ப்பித்தல்"
      },
      stage1Title: "நடந்ததை அறத்திடம் கூறுங்கள்",
      stage1Desc: "உங்கள் பிரச்சினையை இயல்பாக விளக்குங்கள். உங்கள் மொழியில் தட்டச்சு செய்யலாம் அல்லது பேசலாம்.",
      tellUsLabel: "நடந்த விவரத்தைக் கூறுங்கள்...",
      minChars: "குறைந்தது 15 எழுத்துகள்",
      tellUsPlaceholder: "நடந்ததை உங்கள் சொந்த வார்த்தைகளில் விளக்குங்கள்... (தமிழ், ஆங்கிலம் அல்லது இந்தியில் பேசலாம் அல்லது எழுதலாம்)",
      speakProblem: "குரலில் கூறவும்",
      listeningClickStop: "கேட்கிறது... (நிறுத்த கிளிக் செய்க)",
      processingSpeech: "பேச்சு உரையாக்கம் செய்யப்படுகிறது...",
      languageLabel: "மொழி:",
      autoDetect: "✨ தானியங்கி கண்டறிதல்",
      primaryBadge: "முதன்மை",
      transcribedNarrative: "உரையாக்கப்பட்ட பிரச்சினை விளக்கம்",
      speechBadge: "{lang} பேச்சு",
      reviewEditTip: "✨ சரிபார்த்து திருத்துக: 'அறம் மூலம் ஆய்வு செய்க' என்பதை கிளிக் செய்வதற்கு முன் பெயர்கள், தொகைகள் அல்லது தேதிகளை நேரடியாக மேலே உள்ள பெட்டியில் திருத்தலாம்.",
      yourDistrict: "உங்கள் மாவட்டம்",
      districtHelp: "உங்கள் மாவட்டம், {district} மாவட்ட சட்ட உதவி மையத்தின் பொருத்தமான உள்ளூர் உதவியை அறம் இணைக்க உதவுகிறது.",
      clearText: "உரையை அழிக்க",
      analyzingLegal: "சட்ட விவரங்கள் ஆய்வு செய்யப்படுகின்றன...",
      analyzeWithAram: "அறம் மூலம் ஆய்வு செய்க →",
      stage2Title: "அறம் AI வழக்கு மதிப்பீடு",
      listenSummary: "சுருக்கத்தைக் கேட்க",
      stopAudio: "ஆடியோவை நிறுத்த",
      formulatedTitle: "உருவாக்கப்பட்ட பிரச்சினைத் தலைப்பு",
      doneEditing: "முடிந்தது",
      editTitle: "தலைப்பைத் திருத்து",
      priorityLabel: "முன்னுரிமை: {priority}",
      caseOverview: "வழக்கு சூழல் & சட்ட மேலோட்டம்",
      partiesIdentified: "அடையாளம் காணப்பட்ட நபர்கள்",
      disputeClaimAmount: "தகராறு கோரிக்கை தொகை",
      timelineDate: "காலவரிசை / நிகழ்வு தேதி",
      reliefQuestion: "நீங்கள் எதிர்பார்க்கும் குறிப்பிட்ட தீர்வு அல்லது நிவாரணம் என்ன?",
      reliefSubtitle: "உங்கள் கோரிக்கை முடிவு",
      reliefPlaceholder: "எடுத்துக்காட்டு: சட்டவிரோத பிடித்தங்கள் ஏதுமின்றி எனது ₹50,000 முன்பணத்தை நில உரிமையாளர் திருப்பித் தர சட்டப் பணிகள் ஆணைக்குழு மூலம் தீர்வு வேண்டும்.",
      speakBtn: "பேசவும்",
      recordingBtn: "பதிவாகிறது...",
      applicableRemedies: "பொருந்தக்கூடிய சட்டப் பரிகாரங்கள்",
      backBtn: "பின்செல்ல",
      continueDocsBtn: "ஆவணங்கள் & ஆதாரங்களுக்குத் தொடரவும் →",
      stage3Title: "ஆவணங்கள் & துணை ஆதாரங்கள்",
      stage3Desc: "தானியங்கி தயார்நிலை மதிப்பாய்விற்கு பத்திரங்கள், அறிவிப்புகள், ரசீதுகள் அல்லது ஒப்பந்தங்களை இணைக்கவும்.",
      ocrIntegrityReview: "ஆதார தயார்நிலை & ஆவண ஒருமைப்பாடு ஆய்வு",
      continueSafetyBtn: "பாதுகாப்பு & உதவிக்குத் தொடரவும் →",
      stage4Title: "பாதுகாப்பு & சட்ட வழிகாட்டி பிரதிநிதித்துவம்",
      stage4Desc: "பாதுகாப்பு விதிகளை அமைத்து சரிபார்க்கப்பட்ட மாவட்ட சட்ட சேவைகள் அதிகார பிரதிநிதித்துவத்தைப் பெறுங்கள்.",
      continueReviewBtn: "சரிபார்த்து சமர்ப்பித்தலுக்குத் தொடரவும் →",
      stage5Title: "குறையைச் சரிபார்த்து சமர்ப்பித்தல்",
      stage5Desc: "வழக்கு எண் ஒதுக்கீடு மற்றும் பிளாக்செயின் தணிக்கைப் பதிவுக்கு முந்தைய இறுதி சரிபார்ப்பு.",
      declarationText: "சட்ட உதவி விதிகளின்படி நான் வழங்கிய தகவல்கள் அனைத்தும் எனது அறிவுக்கு எட்டியவரை உண்மை என உறுதியளிக்கிறேன்.",
      submitGrievanceBtn: "சட்ட உதவி மையத்தில் குறையைச் சமர்ப்பிக்க →",
      submittingBtn: "சட்டப் பதிவகத்தில் பதிவு செய்யப்படுகிறது...",
      successTitle: "குறை வெற்றிகரமாக பதிவு செய்யப்பட்டது!",
      successDesc: "உங்கள் குறை தமிழ்நாடு சட்டப் பணிகள் ஆணைக்குழுவில் பதிவு செய்யப்பட்டு, பிளாக்செயின் தணிக்கைத் தொகுதியில் பாதுகாப்பாகப் பதியப்பட்டுள்ளது.",
      officialRef: "அதிகாரப்பூர்வ வழக்கு குறிப்பு எண்:",
      trackGrievanceBtn: "புகார் நிலையை அறிய",
      returnDashboardBtn: "டாஷ்போர்டுக்குத் திரும்ப"
    },
    complaintHistory: {
      title: "எனது புகார்களின் வரலாறு",
      subtitle: "பதிவு செய்யப்பட்ட அனைத்து வழக்குகளின் நிலை, ஆதார சரிபார்ப்பு மற்றும் சட்ட வழிகாட்டி குறிப்புகளைக் கண்காணிக்கவும்.",
      newGrievanceBtn: "புதிய குறை சமர்ப்பிக்க",
      searchPlaceholder: "தலைப்பு, எண் அல்லது விவரம் மூலம் தேடவும்...",
      filterAll: "அனைத்து நிலைகளும்",
      filterSubmitted: "சமர்ப்பிக்கப்பட்டது",
      filterInProgress: "செயலில் உள்ளது",
      filterResolved: "தீர்வு காணப்பட்டது",
      noComplaintsTitle: "செயலில் உள்ள புகார்கள் ஏதுமில்லை",
      noComplaintsDesc: "நீங்கள் இன்னும் எந்தப் புகாரையும் பதிவு செய்யவில்லை அல்லது உங்கள் தேடலுடன் பொருந்தவில்லை.",
      fileFirstGrievance: "முதல் புகாரைப் பதிவு செய்க"
    },
    evidenceVault: {
      title: "ஆவணங்கள் & ஆதாரப் பெட்டகம்",
      subtitle: "பத்திரங்கள், ஒப்பந்தங்கள், நோட்டீஸ் மற்றும் FIR நகல்களை உடனடி OCR சரிபார்ப்பிற்கு பதிவேற்றி குறியாக்கப்பட்ட பாதுகாப்பில் சேமிக்கவும்.",
      analyzerTitle: "OCR ஆவண சட்ட தயார்நிலை மதிப்பாய்வி",
      analyzerSubtitle: "பதிவு எண்கள், எல்லை விவரங்கள் மற்றும் அரசு முத்திரைகளை சமர்ப்பிப்பதற்கு முன் சரிபார்க்கவும்.",
      uploadBoxTitle: "பதிவேற்ற கிளிக் செய்யவும் அல்லது கோப்பை இழுத்துப் போடவும்",
      uploadBoxSubtitle: "PDF, JPG, JPEG, PNG (அதிகபட்சம் 15MB)",
      verifyBtn: "ஆவணத் தயார்நிலையைச் சரிபார்க்க",
      verifyingBtn: "ஆவணம் OCR ஆய்வு செய்யப்படுகிறது...",
      readinessScore: "சட்டத் தயார்நிலை மதிப்பீடு",
      detectedEntities: "கண்டறியப்பட்ட சட்ட விவரங்கள்"
    },
    trackComplaint: {
      title: "புகார் மைல்கல் நிலையைக் கண்காணிக்க",
      subtitle: "உங்கள் வழக்கு முன்னேற்றம், நியமிக்கப்பட்ட வழிகாட்டி மற்றும் அடுத்த கட்ட நடவடிக்கைகளை அறிய ARAM குறிப்பு எண்ணை உள்ளிடவும்.",
      inputPlaceholder: "வழக்கு குறிப்பு எண்ணை உள்ளிடவும் (எ.கா. ARAM-2026-000001 அல்லது 1)...",
      trackBtn: "நிலையை அறிய",
      trackingBtn: "தேடுகிறது...",
      step1Title: "குறை பதிவு செய்யப்பட்டது",
      step1Desc: "அறம் அதிகாரப்பூர்வ பதிவகத்தில் பாதுகாப்பாகச் சமர்ப்பிக்கப்பட்டது",
      step2Title: "AI ஆய்வு & வகைப்பாடு",
      step2Desc: "பொருந்தக்கூடிய சட்டப் பிரிவுகள் மற்றும் ஆவணப் பட்டியல் கண்டறியப்பட்டது",
      step3Title: "சட்ட வழிகாட்டி நியமனம்",
      step3Desc: "உதவிக்காக சரிபார்க்கப்பட்ட சட்ட வழிகாட்டி ஒதுக்கப்பட்டுள்ளார்",
      step4Title: "அதிகாரப்பூர்வ தீர்வு",
      step4Desc: "வட்டம் / மாவட்ட சட்ட நடவடிக்கைகள் நிறைவடைந்தன"
    },
    helpCenter: {
      title: "சட்ட உரிமைகள் & அவசர உதவி மையம்",
      subtitle: "சான்றளிக்கப்பட்ட சட்ட உதவி எண்கள், மாவட்ட சட்ட சேவைகள் ஆணையம் (DLSA) மற்றும் வழிகாட்டுதல்கள்.",
      nalsaTitle: "தேசிய சட்ட சேவைகள் ஆணையம் (NALSA)",
      nalsaDesc: "சட்ட சேவைகள் அதிகாரச் சட்டத்தின் கீழ் தகுதியுடைய குடிமக்களுக்கு இலவச சட்ட உதவி",
      womenTitle: "பெண்கள் உதவி எண்",
      womenDesc: "குடும்ப வன்முறை மற்றும் அவசரப் பாதுகாப்பிற்கான 24x7 நேரடி உதவி",
      cyberTitle: "தேசிய சைபர் குற்றப் பதிவு மையம்",
      cyberDesc: "நிதி மோசடி மற்றும் இணைய துன்புறுத்தல் குறித்த உடனடிப் புகார்",
      seniorTitle: "மூத்த குடிமக்கள் உதவி எண்",
      seniorDesc: "முதியோர் வன்கொடுமை மற்றும் பராமரிப்பு தகராறுகளுக்கான சட்ட உதவி",
      gatewayTitle: "அறம் அதிகாரப்பூர்வ ஆதரவு நுழைவாயில்",
      gatewayDesc: "மனு வரைவு தொடர்பான கேள்விகள் அல்லது தொழில்நுட்ப உதவிக்கு எங்களை மின்னஞ்சல் மூலம் தொடர்பு கொள்ளவும்:"
    },
    auth: {
      layout: {
        mobileBadge: "தமிழ்நாடு சட்ட வழிகாட்டி",
        mobileSubtitle: "அணுகக்கூடிய உரிமைகள் & உதவி மேலாண்மை அமைப்பு",
        mobileFooter: "முழுமையான குறியாக்கம் • தமிழ்நாடு அரசு குடிமக்கள் உதவி"
      },
      banner: {
        govtTag: "தமிழ்நாடு அரசு & குடிமக்கள் சட்ட உதவி",
        copilotDesc: "அணுகக்கூடிய உரிமைகள் & உதவி மேலாண்மை அமைப்பு • AI சட்ட வழிகாட்டி",
        slide1Badge: "உறுதியான AI சட்டப் பகுப்பாய்வு",
        slide1Title: "ஒவ்வொரு குடிமகனுக்கும் உறுதியான சட்ட வழிகாட்டல்",
        slide1Desc: "சான்றளிக்கப்பட்ட இந்திய சட்ட அறிவு, குற்றவியல் பிரிவுகள் மற்றும் சட்டங்களின் அடிப்படையில் தமிழ், தங்கிலீஷ், இந்தி மற்றும் ஆங்கிலத்தில் உடனடி சட்டப் பகுப்பாய்வு.",
        slide2Badge: "அமைப்புசார் பாதுகாப்பு",
        slide2Title: "குறியாக்கப்பட்ட நேரடி அதிகாரப்பூர்வ புகார் பதிவு",
        slide2Desc: "வட்டார அலுவலகங்கள், மாவட்ட சட்டப் பணிகள் ஆணைக்குழு (DLSA) மற்றும் சான்றளிக்கப்பட்ட வழக்கறிஞர்களுடன் தடையின்றி இணையுங்கள்.",
        slide3Badge: "பன்மொழி தளம்",
        slide3Title: "குரல்வழி பன்மொழி அணுகல்",
        slide3Desc: "தமிழ், இந்தி மற்றும் ஆங்கிலத்தில் உங்கள் தாய்மொழியில் இயல்பாகப் பேசி வழிகாட்டல் பெறுங்கள்.",
        trust1: "சான்றளிக்கப்பட்ட உண்மை சட்ட விதிகள்",
        trust2: "சரிபார்க்கப்பட்ட DLSA & வட்டார பகிர்வு",
        trust3: "ரகசியமான 256-பிட் குறியாக்கப்பட்ட ஆய்வு",
        officialSupport: "அதிகாரப்பூர்வ உதவி:",
        compliance: "இந்திய தகவல் தொழில்நுட்பச் சட்டம் & DPDP 2023 இணக்கமானது",
        of: "/"
      },
      login: {
        backHome: "முகப்புக்குத் திரும்ப",
        portalBadge: "ஒருங்கிணைந்த குடிமக்கள் தளம்",
        title: "உள்நுழைக",
        subtitle: "உங்கள் சட்ட உதவிப் பதிவுகள், புகார்கள் மற்றும் வழிகாட்டுதல் வழக்குகளை அணுகவும்.",
        emailLabel: "மின்னஞ்சல் முகவரி",
        emailPlaceholder: "name@example.com",
        passwordLabel: "கடவுச்சொல்",
        passwordPlaceholder: "••••••••••••",
        forgotPassword: "கடவுச்சொல்லை மறந்துவிட்டீர்களா?",
        rememberMe: "30 நாட்களுக்கு இந்தச் சாதனத்தை நினைவில் கொள்க",
        signInBtn: "கணக்கில் உள்நுழைக",
        signingIn: "உள்நுழைகிறது...",
        orContinueWith: "அல்லது இதன் மூலம் தொடரவும்",
        googleSignIn: "கூகிள் மூலம் உள்நுழைக",
        quickDemo: "டெமோ கணக்கு விவரங்கள்",
        hideDemo: "டெமோ கணக்குகளை மறை",
        roleCitizen: "குடிமகன்",
        roleAdmin: "சேலம் நிர்வாகி",
        roleGuide: "சேலம் வழிகாட்டி",
        roleSuperAdmin: "தலைமை நிர்வாகி",
        demoHint: "எந்த மாவட்டமும் பொருந்தும்: <மாவட்டம்>.admin@gmail.com / Admin@123 & <மாவட்டம்>.guide1@gmail.com / Admin@123",
        noAccount: "இன்னும் கணக்கு இல்லையா?",
        createAccount: "இலவச குடிமக்கள் கணக்கை உருவாக்க →",
        emailPasswordRequired: "உங்கள் மின்னஞ்சல் மற்றும் கடவுச்சொல் இரண்டையும் உள்ளிடவும்.",
        loginSuccess: "அறம் AI சட்ட உதவிக்கு மீண்டும் வரவேற்கிறோம்!",
        invalidCredentials: "தவறான மின்னஞ்சல் அல்லது கடவுச்சொல். உங்கள் விவரங்களை சரிபார்க்கவும்."
      },
      forgotPassword: {
        backSignIn: "உள்நுழைவுக்குத் திரும்ப",
        badge: "கணக்கு பாதுகாப்பு மீட்பு",
        title: "கடவுச்சொல்லை மீட்டமைக்க",
        subtitle: "பாதுகாப்பான 6-இலக்க OTP பெற உங்கள் பதிவுசெய்த மின்னஞ்சல் அல்லது 10-இலக்க மொபைல் எண்ணை உள்ளிடவும்.",
        inputLabel: "மின்னஞ்சல் அல்லது மொபைல் எண்",
        inputPlaceholder: "name@example.com அல்லது 9876543210",
        sendOtp: "சரிபார்ப்பு OTP அனுப்புக",
        sendingOtp: "OTP அனுப்பப்படுகிறது...",
        accountNotFound: "கணக்கு காணப்படவில்லை",
        verificationError: "சரிபார்ப்பு பிழை",
        createNewAccount: "புதிய கணக்கு தொடங்க"
      },
      register: {
        backSignIn: "உள்நுழைவுக்குத் திரும்ப",
        badge: "அதிகாரப்பூர்வ குடிமக்கள் பதிவு",
        title: "குடிமக்கள் கணக்கை உருவாக்க",
        subtitle: "AI சட்ட பகுப்பாய்வு, வழக்கைக் கண்காணித்தல் மற்றும் சட்ட வழிகாட்டி உதவி பெற தமிழ்நாடு சட்ட உதவி தளத்தில் இணையுங்கள்.",
        fullName: "முழுப் பெயர்",
        fullNamePlaceholder: "எ.கா. அன்பரசன் கே",
        email: "மின்னஞ்சல் முகவரி",
        emailPlaceholder: "name@example.com",
        mobile: "மொபைல் எண்",
        mobilePlaceholder: "9876543210",
        district: "மாவட்டம்",
        password: "கடவுச்சொல்",
        confirmPassword: "கடவுச்சொல்லை உறுதிப்படுத்துக",
        terms: "சேவை விதிமுறைகள் மற்றும் தனியுரிமைக் கொள்கைகளை ஏற்கிறேன்",
        submitBtn: "இலவச கணக்கை உருவாக்க",
        submitting: "கணக்கு உருவாக்கப்படுகிறது...",
        alreadyAccount: "ஏற்கனவே கணக்கு உள்ளதா?",
        signInLink: "உள்நுழைக →"
      },
      otp: {
        backSignIn: "உள்நுழைவுக்குத் திரும்ப",
        badge: "இரு காரணி அங்கீகரிப்பு",
        title: "OTP குறியீட்டைச் சரிபார்க்கவும்",
        subtitle: "உங்கள் பதிவுசெய்த மொபைல் மற்றும் மின்னஞ்சலுக்கு அனுப்பப்பட்ட 6-இலக்க குறியீட்டை உள்ளிடவும்.",
        verifyBtn: "OTP சரிபார்த்து தொடரவும்",
        verifying: "சரிபார்க்கப்படுகிறது...",
        resendIn: "{seconds} வினாடிகளில் மீண்டும் அனுப்பலாம்",
        resendBtn: "குறியீட்டை மீண்டும் அனுப்ப",
        otpRequired: "6-இலக்க OTP குறியீட்டை உள்ளிடவும்."
      },
      google: {
        title: "கூகிள் மூலம் உள்நுழைக",
        subtitle: "அறம் தளத்தில் தொடர ஒரு கணக்கைத் தேர்ந்தெடுக்கவும்",
        badge: "சரிபார்க்கப்பட்ட அதிகாரப்பூர்வ அணுகல்",
        desc: "உங்கள் டாஷ்போர்டைத் தொடர அங்கீகரிக்கப்பட்ட சுயவிவரத்தைத் தேர்ந்தெடுக்கவும்.",
        verifiedProfiles: "சரிபார்க்கப்பட்ட கணக்குகள்",
        customAccount: "தனிப்பயன் கூகிள் மின்னஞ்சல்",
        useAnother: "மற்றொரு கூகிள் கணக்கைப் பயன்படுத்தவும்",
        emailLabel: "கூகிள் மின்னஞ்சல் முகவரி",
        emailPlaceholder: "yourname@gmail.com",
        nameLabel: "முழுப் பெயர் (விருப்பத்திற்குரியது)",
        namePlaceholder: "எ.கா. ஆனந்த கிருஷ்ணன்",
        continueBtn: "இந்த கூகிள் கணக்குடன் தொடரவும்",
        verifyingBtn: "கூகிள் கணக்கு சரிபார்க்கப்படுகிறது...",
        securityNote: "இந்திய தகவல் தொழில்நுட்பச் சட்டம் & DPDP 2023 இணக்கமானது",
        continueAs: "{name} என தொடரவும்",
        cancel: "ரத்து செய்",
        citizenBadge: "சரிபார்க்கப்பட்ட குடிமகன்",
        guideBadge: "சட்ட வழிகாட்டி",
        adminBadge: "மண்டல நிர்வாகி",
        superAdminBadge: "மாநில தலைமை நிர்வாகி"
      }
    }
  },
  "hi-IN": {
    nav: {
      home: "होम",
      about: "परिचय",
      services: "सेवाएं",
      howItWorks: "ARAM कैसे काम करता है",
      trackCase: "मामला ट्रैक करें",
      trackGrievance: "शिकायत ट्रैक करें",
      contact: "संपर्क",
      signIn: "साइन इन",
      dashboard: "डैशबोर्ड",
      askAi: "ARAM AI से पूछें"
    },
    hero: {
      badge: "नागरिक कानूनी सहायता और शिकायत निवारण",
      eyebrow: "हर नागरिक के लिए सुलभ न्याय",
      title1: "आपके अधिकार। हमारा समर्थन।",
      title2: "एक न्यायपूर्ण कल।",
      subtitle: "ARAM नागरिकों को कानूनी जानकारी समझने, सही अधिकारियों की पहचान करने, साक्ष्य व्यवस्थित करने और प्रमाणित कानूनी मार्गदर्शकों से जुड़ने में मदद करता है — तमिल, अंग्रेजी और हिंदी में।",
      askAi: "ARAM AI से पूछें",
      fileGrievance: "शिकायत दर्ज करें",
      trackCase: "मामला ट्रैक करें",
      speakProblem: "समस्या बोलें",
      listening: "सुन रहा है... समाप्त करने के लिए क्लिक करें",
      uploadDoc: "दस्तावेज़ अपलोड करें",
      connectGuide: "मार्गदर्शक से जुड़ें",
      noLegalFees: "कोई कानूनी शुल्क नहीं",
      piiPrivacy: "कड़ी गोपनीयता सुरक्षा",
      dlsaAligned: "तमिलनाडु DLSA से संबद्ध"
    },
    trustStrip: {
      multilingual: "त्रिभाषी कानूनी सहायता",
      multilingualDesc: "तमिल • अंग्रेजी • हिंदी",
      verified: "सत्यापित कानूनी स्रोतों पर आधारित",
      verifiedDesc: "प्रमाणित भारतीय कानूनी धाराएं",
      humanSupport: "मानव मार्गदर्शक एवं DLSA सहायता",
      humanSupportDesc: "अधिकृत कानूनी प्रतिनिधित्व",
      districtAware: "38 जिलों के लिए मार्गदर्शन",
      districtAwareDesc: "तमिलनाडु के सभी 38 जिले",
      liveRegistry: "राज्यव्यापी लाइव नागरिक रजिस्ट्री डेटा",
      platformIndicators: "राज्यव्यापी नागरिक मंच संकेतक",
      verifiedRealTime: "सत्यापित रीयल-टाइम संख्या",
      tnGovInitiative: "तमिलनाडु सरकार • कानूनी सहायता पहल",
      totalComplaints: "कुल शिकायतें",
      acrossDistricts: "38 जिलों में",
      activeInReview: "समीक्षाधीन मामले",
      underDlsa: "DLSA प्रक्रिया के तहत",
      resolvedCases: "निपटाए गए मामले",
      citizensHelped: "सहायता प्राप्त नागरिक",
      legalGuides: "कानूनी मार्गदर्शक",
      acrossTn: "पूरे तमिलनाडु में",
      quote: "“न्याय तक पहुंच लोकतंत्र को मजबूत बनाती है।”",
      quoteAuthor: "— राष्ट्रीय कानूनी सेवा प्राधिकरण (NALSA)"
    },
    waysToGetHelp: {
      tag: "सहायता प्राप्त करने के तरीके",
      title: "शुरुआत करने का तरीका चुनें",
      subtitle: "हर नागरिक अपनी सुविधा अनुसार सहायता प्राप्त कर सकता है।",
      civicAssistance: "मुफ्त नागरिक सहायता • कोई छिपा हुआ शुल्क नहीं",
      speakTitle: "बोलें",
      speakSubtitle: "वॉयस-प्रथम सहायता",
      speakDesc: "अपनी भाषा में बोलकर अपनी समस्या विस्तार से बताएं।",
      speakAction: "बोलने के लिए टैप करें",
      speakListening: "सुन रहे हैं...",
      speakBadge: "तमिल • हिंदी • अंग्रेजी",
      typeTitle: "लिखें",
      typeSubtitle: "संवादात्मक AI चैट",
      typeDesc: "अपनी समस्या लिखकर समझाएं और कानूनी स्थिति समझें।",
      typeAction: "AI से चैट करें",
      typeBadge: "24/7 उपलब्ध",
      uploadTitle: "दस्तावेज़ अपलोड",
      uploadSubtitle: "साक्ष्य और नोटिस",
      uploadDesc: "विलेख, नोटिस या रसीदें अपलोड करके कानूनी तत्परता जांचें।",
      uploadAction: "दस्तावेज़ जांचें",
      uploadBadge: "गहन OCR तैयार",
      connectTitle: "गाइड से जुड़ें",
      connectSubtitle: "मानव कानूनी गाइड",
      connectDesc: "जिला कानूनी सेवा प्राधिकरण (DLSA) के मान्यता प्राप्त गाइड से जुड़ें।",
      connectAction: "गाइड खोजें",
      connectBadge: "DLSA मान्यता प्राप्त"
    },
    aiHuman: {
      tag: "AI और मानवीय सहयोग",
      title: "जहाँ संभव हो AI। जहाँ आवश्यक हो मानवीय सहायता।",
      subtitle: "बुद्धिमान AI विश्लेषण की गति और प्रमाणित कानूनी मार्गदर्शकों का विश्वसनीय निर्णय।",
      desc1: "ARAM AI तुरंत आपके मामले के तथ्यों को व्यवस्थित करता है, प्रासंगिक धाराओं की पहचान करता है, आवश्यक साक्ष्य चेकलिस्ट तैयार करता है और दस्तावेजों की जांच करता है।",
      desc2: "जब आपके मामले में कानूनी मसौदा तैयार करने, औपचारिक याचिका दायर करने या DLSA प्रतिनिधित्व की आवश्यकता होती है, तो प्रमाणित कानूनी मार्गदर्शक सीधे आपकी सहायता करते हैं।",
      bullet1: "24x7 तत्काल प्रारंभिक कानूनी विश्लेषण और अधिकारों की स्पष्ट व्याख्या",
      bullet2: "कोई स्वचालित अस्वीकृति नहीं — प्रत्येक जटिल मामले के लिए मानवीय समीक्षा",
      bullet3: "तालुक और जिला विधिक सेवा प्राधिकरण (DLSA) के साथ सीधा समन्वय",
      aiTitle: "AI कानूनी सहायता",
      aiSubtitle: "24/7 त्वरित प्राथमिक मार्गदर्शन",
      humanTitle: "मानव कानूनी सहायता",
      humanSubtitle: "मान्यता प्राप्त DLSA और कानूनी गाइड",
      startAi: "AI विश्लेषण शुरू करें",
      requestGuide: "कानूनी गाइड का अनुरोध करें"
    },
    immediateHelp: {
      tag: "आपातकालीन एवं वैधानिक हेल्पलाइन",
      title: "क्या आपको तत्काल सहायता चाहिए?",
      subtitle: "आपातकाल, महिला सुरक्षा, साइबर अपराध और मुफ्त कानूनी सहायता के लिए आधिकारिक सरकारी हेल्पलाइन।",
      emergency: "आपातकालीन सेवाएं (पुलिस / एम्बुलेंस)",
      emergencySub: "पुलिस, अग्निशमन और एम्बुलेंस (24x7)",
      women: "महिला हेल्पलाइन",
      womenSub: "सुरक्षा एवं घरेलू हिंसा निवारण (24x7)",
      cyber: "साइबर अपराध रिपोर्टिंग",
      cyberSub: "राष्ट्रीय वित्तीय धोखाधड़ी हेल्पलाइन",
      legalAid: "मुफ्त कानूनी सहायता (NALSA)",
      legalAidSub: "विधिक सेवा प्राधिकरण (DLSA) सेवाएं"
    },
    howItWorks: {
      tag: "नागरिक कानूनी यात्रा",
      title: "ARAM कैसे सहायता करता है",
      subtitle: "पहले प्रश्न से लेकर अधिकृत कानूनी सहायता तक — सरल, पारदर्शी और कानून पर आधारित।",
      notice: "ARAM एक प्रशासनिक और कानूनी जागरूकता मंच है, यह कोई न्यायालय नहीं है। सभी औपचारिक प्रतिनिधित्व अधिकृत कानूनी मार्गदर्शकों के माध्यम से ही होते हैं।",
      phase: "चरण",
      step1Title: "ARAM को बताएं",
      step1Subtitle: "सरल इनपुट",
      step1Desc: "तमिल, अंग्रेजी या हिंदी में बोलकर या लिखकर अपनी समस्या बताएं।",
      step2Title: "अपने मामले को समझें",
      step2Subtitle: "कानूनी विश्लेषण",
      step2Desc: "ARAM तथ्यों का विश्लेषण कर प्रासंगिक कानूनी धाराओं और दंड प्रावधानों की पहचान करता है।",
      step3Title: "सत्यापित मार्गदर्शन पाएं",
      step3Subtitle: "साक्ष्य और नियम",
      step3Desc: "सत्यापित कानूनी प्रावधान, प्राधिकरण मार्ग और साक्ष्य चेकलिस्ट तैयार की जाती है।",
      step4Title: "मानव सहायता",
      step4Subtitle: "DLSA और कानूनी गाइड",
      step4Desc: "मामले अधिकृत कानूनी मार्गदर्शकों और विधिक सेवा प्राधिकरण (DLSA) को भेजे जाते हैं।",
      step5Title: "मामला ट्रैक करें",
      step5Subtitle: "पूर्ण पारदर्शिता",
      step5Desc: "लाइव प्रगति देखें, WhatsApp/SMS अपडेट प्राप्त करें और आधिकारिक PDF डाउनलोड करें।"
    },
    features: {
      tag: "न्याय के लिए समर्पित",
      title: "ARAM AI आपके कानूनी अधिकारों की रक्षा कैसे करता है",
      subtitle: "प्रमाणित भारतीय कानूनों के आधार पर सटीक और त्रुटिहीन कानूनी मार्गदर्शन।",
      f1Title: "11-भाग संरचित कानूनी विश्लेषण",
      f1Desc: "प्रत्येक प्रश्न पर कानूनी धाराएं, अगले कदम, दस्तावेज़ चेकलिस्ट और DLSA मार्गदर्शन दिया जाता है।",
      f2Title: "बहुभाषी वॉयस असिस्टेंट",
      f2Desc: "तमिल, हिंदी और अंग्रेजी में सीधे बोलकर शिकायत दर्ज करें और मार्गदर्शन पाएं।",
      f3Title: "दस्तावेज़ OCR सत्यापन",
      f3Desc: "दस्तावेजों की स्वचालित जांच और कानूनी तत्परता स्कोरिंग।",
      f4Title: "प्रमाणित कानूनी मार्गदर्शक",
      f4Desc: "AI विश्लेषण से सीधे स्थानीय कानूनी मार्गदर्शकों और DLSA को त्वरित अग्रेषण।"
    },
    about: {
      tag: "हमारा उद्देश्य",
      title: "हर नागरिक के लिए कानूनी अधिकारों का लोकतंत्रीकरण",
      desc1: "ARAM (अறம்) इस मूल विश्वास पर आधारित है कि भाषा, क्षेत्र या आर्थिक स्थिति न्याय में बाधा नहीं बननी चाहिए।",
      desc2: "नागरिकों को प्रमाणित कानूनी ज्ञान और सत्यापित मार्गदर्शकों से जोड़कर ARAM समान न्याय सुनिश्चित करता है।",
      commitmentsTitle: "ARAM की मुख्य प्रतिबद्धताएं",
      c1: "सटीक मार्गदर्शन: सभी कानूनी सलाह प्रमाणित कानूनों के अनुसार सत्यापित हैं।",
      c2: "गोपनीयता सुरक्षा: आधार और व्यक्तिगत विवरणों की स्वचालित सुरक्षा।",
      c3: "आधिकारिक ईमेल: ouraramsupport@gmail.com से सुरक्षित व नियमित संचार।"
    },
    whoCanUse: {
      tag: "हितधारक पारिस्थितिकी तंत्र",
      title: "ARAM का उपयोग कौन कर सकता है?",
      subtitle: "सार्वजनिक कानूनी जागरूकता और शिकायत निवारण से जुड़े सभी पक्षों को जोड़ने के लिए निर्मित।",
      tagPublic: "सार्वजनिक पहुंच",
      tagAssistance: "मामला सहायता",
      tagAuthority: "प्राधिकरण समीक्षा",
      tagGovernance: "प्रशासन",
      u1Title: "नागरिक",
      u1Desc: "अपनी पसंदीदा भाषा में शिकायत दर्ज करें, कानूनी अधिकार समझें और घर बैठे प्रगति ट्रैक करें।",
      u2Title: "कानूनी गाइड और स्वयंसेवक",
      u2Desc: "नागरिकों को याचिका तैयार करने में सहायता करने वाले अधिकृत पैरालीगल और कानूनी स्वयंसेवक।",
      u3Title: "सरकारी अधिकारी",
      u3Desc: "सत्यापित साक्ष्यों के साथ संरचित शिकायतें प्राप्त कर समाधान करने वाले विभागीय व DLSA अधिकारी।",
      u4Title: "मंच प्रशासक",
      u4Desc: "जिला-स्तरीय शिकायत निवारण, ऑडिट ट्रेल्स और कानूनी सेवा गुणवत्ता की निगरानी करने वाले पर्यवेक्षक।"
    },
    cta: {
      title: "क्या आप अपने अधिकारों को जानने के लिए तैयार हैं?",
      subtitle: "अपना पहला कानूनी प्रश्न पूछें, दस्तावेज़ सत्यापित करें या आज ही मार्गदर्शक से जुड़ें।",
      button: "निःशुल्क कानूनी मार्गदर्शन शुरू करें",
      tag: "कानूनी समाधान शुरू करें",
      heading: "शुरुआत कहाँ से करें समझ नहीं आ रहा?",
      desc: "ARAM को बताएं कि क्या हुआ। हम आपके अधिकारों को समझने, दस्तावेज़ तैयार करने और अगले कदम तय करने में मदद करेंगे।",
      askAi: "ARAM AI से पूछें",
      fileGrievance: "शिकायत दर्ज करें",
      footerNote: "मुफ्त लोक सेवा • पूर्ण गोपनीयता • भारतीय कानून पर आधारित"
    },
    immediateHelp: {
      tag: "आपातकालीन एवं वैधानिक सहायता",
      title: "तत्काल सहायता की आवश्यकता है?",
      subtitle: "आपात स्थिति, महिला सुरक्षा, साइबर अपराध और मुफ्त कानूनी सहायता के लिए आधिकारिक सरकारी हेल्पलाइन।",
      emergency: "आपातकालीन सेवाएं",
      emergencySub: "पुलिस, अग्निशमन एवं एम्बुलेंस (24x7)",
      badgeEmergency: "राष्ट्रीय आपातकाल",
      women: "महिला हेल्पलाइन",
      womenSub: "सुरक्षा एवं घरेलू हिंसा सहायता (24x7)",
      badgeWomen: "महिला सुरक्षा",
      cyber: "साइबर अपराध हेल्पलाइन",
      cyberSub: "राष्ट्रीय वित्तीय धोखाधड़ी रिपोर्टिंग",
      badgeCyber: "साइबर धोखाधड़ी",
      legalAid: "NALSA कानूनी सहायता",
      legalAidSub: "मुफ्त कानूनी सहायता एवं DLSA सेवाएं",
      badgeLegalAid: "मुफ्त कानूनी सहायता",
      tapToCall: "कॉल करने के लिए टैप करें {number}"
    },
    civicFeatures: {
      petitionTitle: "दाखिल करने हेतु तैयार औपचारिक याचिका",
      petitionSub: "सक्षम प्राधिकारी को प्रस्तुत करने हेतु संरचित औपचारिक वैधानिक आवेदन।",
      btnGeneratePetition: "औपचारिक याचिका प्रारूप तैयार करें",
      btnPrintPetition: "याचिका प्रिंट करें (Print)",
      btnCopyPetition: "याचिका पाठ कॉपी करें",
      langTamil: "तमिल में प्रारूप",
      langEnglish: "अंग्रेजी में प्रारूप",
      petitionFrom: "प्रेषक (याचिकाकर्ता):",
      petitionTo: "सेवा में (सक्षम प्राधिकारी):",
      petitionSubject: "विषय:",
      petitionFacts: "शिकायत के मुख्य तथ्य:",
      petitionProvisions: "लागू कानूनी धाराएं एवं संदर्भ:",
      petitionPrayer: "प्रार्थना / चाहा गया निवारण:",
      petitionVerification: "मैं सत्यनिष्ठा से सत्यापित करता/करती हूं कि ऊपर वर्णित सभी तथ्य मेरी जानकारी और विश्वास के अनुसार सत्य हैं।",
      petitionSignature: "याचिकाकर्ता के हस्ताक्षर / अंगूठा निशान",
      
      sec12Title: "NALSA धारा 12 मुफ्त कानूनी सहायता पात्रता",
      sec12Sub: "विधिक सेवा प्राधिकरण अधिनियम 1987 के तहत 100% मुफ्त सरकारी अधिवक्ता प्रतिनिधित्व की पात्रता जांचें।",
      btnCheckSec12: "मुफ्त कानूनी सहायता पात्रता जांचें",
      sec12Q1: "क्या आप महिला हैं या 18 वर्ष से कम आयु के बच्चे हैं?",
      sec12Q2: "क्या आप अनुसूचित जाति (SC) या अनुसूचित जनजाति (ST) से हैं?",
      sec12Q3: "क्या आप दिव्यांग हैं या आपदा/हिंसा के शिकार हैं?",
      sec12Q4: "क्या आपकी वार्षिक पारिवारिक आय ₹3,00,000 से कम है?",
      sec12Eligible: "100% मुफ्त कानूनी सहायता हेतु पात्र",
      sec12EligibleDesc: "आप सरकारी खर्च पर DLSA पैनल अधिवक्ता के माध्यम से न्यायालयीन प्रतिनिधित्व हेतु वैधानिक रूप से पात्र हैं।",
      sec12NotEligible: "सामान्य कानूनी मार्गदर्शन मोड",
      sec12NotEligibleDesc: "यद्यपि आप न्यायालयीन अधिवक्ता हेतु धारा 12 के अंतर्गत पात्र नहीं हो सकते, ARAM AI मार्गदर्शन पूर्णतः मुफ्त रहेगा।",
      
      ratingTitle: "नागरिक संतुष्टि एवं समाधान समीक्षा",
      ratingSub: "आपकी शिकायत के समाधान और कानूनी सहायता की आधिकारिक समीक्षा।",
      rateExperience: "आप अपनी शिकायत के समाधान को कैसे आंकेंगे?",
      wasHelpful: "क्या कानूनी गाइड द्वारा दिया गया मार्गदर्शन उपयोगी था?",
      yesHelpful: "हाँ, बहुत उपयोगी",
      noHelpful: "सुधार की आवश्यकता है",
      feedbackPlaceholder: "समाधान के संबंध में अपनी टिप्पणी दर्ज करें...",
      btnSubmitRating: "समाधान की पुष्टि करें एवं फीडबैक भेजें",
      lowRatingAlert: "क्या आप इस समाधान से संतुष्ट नहीं हैं?",
      lowRatingDesc: "यदि आपकी समस्या का समाधान उचित नहीं हुआ, तो आपके पास जिला प्रशासन समीक्षा हेतु अपील करने का कानूनी अधिकार है।",
      btnAppealReopen: "औपचारिक अपील दायर करें / मामला पुनः खोलें",
      alreadyRated: "आपने इस समाधान का मूल्यांकन किया है ({stars}/5 सितारे)",
      
      appointmentTitle: "10-मिनट मार्गदर्शन कॉल का अनुरोध करें",
      appointmentSub: "अपने आवंटित कानूनी गाइड के साथ टेलीफोनिक परामर्श निर्धारित करें।",
      btnRequestCall: "परामर्श कॉल का अनुरोध करें",
      selectMode: "परामर्श माध्यम",
      modePhone: "फोन कॉल (मोबाइल)",
      modeApp: "इन-ऐप वॉइस कॉल",
      modeWa: "व्हाट्सएप वॉइस/टेक्स्ट मार्गदर्शन",
      selectSlot: "पसंदीदा समय अंतराल",
      slotMorning: "सुबह (10:00 AM – 01:00 PM)",
      slotAfternoon: "दोपहर (02:00 PM – 05:00 PM)",
      slotEvening: "शाम (05:00 PM – 08:00 PM)",
      appointmentNote: "विशिष्ट प्रश्न जिसे आप चर्चा करना चाहते हैं",
      btnSubmitAppointment: "कॉल अनुरोध की पुष्टि करें",
      appointmentActive: "मार्गदर्शन कॉल का अनुरोध किया गया है",
      
      lokAdalatTitle: "लोक अदालत पूर्व-मुकदमेबाजी हेतु पात्र",
      lokAdalatDesc: "यह विवाद बिना किसी न्यायालय शुल्क के राष्ट्रीय/तालुका लोक अदालत के माध्यम से सुलझाया जा सकता है, जो सिविल कोर्ट डिक्री के समान बाध्यकारी है।",
      
      atrTitle: "आधिकारिक कार्रवाई रिपोर्ट (ATR)",
      atrSub: "आवंटित कानूनी गाइड / जिला प्राधिकारी द्वारा जारी वैधानिक समापन पत्र।",
      atrVerified: "वैधानिक सत्यापन पूर्ण"
    },
    sidebar: {
      portalTitle: "कानूनी सहायता पोर्टल",
      dashboard: "डैशबोर्ड",
      askAi: "ARAM AI से पूछें",
      submitGrievance: "शिकायत दर्ज करें",
      myGrievances: "मेरी शिकायतें",
      documentsEvidence: "दस्तावेज़ और साक्ष्य",
      trackStatus: "स्थिति ट्रैक करें",
      supportSettings: "सहायता और सेटिंग्स",
      notifications: "सूचनाएं",
      helpRights: "सहायता और अधिकार मार्गदर्शिका",
      profileSettings: "प्रोफाइल और सेटिंग्स",
      signOut: "साइन आउट"
    },
    topbar: {
      searchCitizen: "ARAM AI से कानूनी प्रश्न पूछें (उदा. भूमि विवाद, RTI, 498A)...",
      searchAdmin: "सभी 38 जिलों में शिकायतें खोजें (आईडी, नागरिक, कीवर्ड)...",
      searchGuide: "आवंटित मामले या कानूनी विषय खोजें...",
      lightMode: "लाइट मोड पर स्विच करें",
      darkMode: "डार्क मोड पर स्विच करें",
      notifications: "सूचनाएं"
    },
    citizenDashboard: {
      portalBadge: "तमिलनाडु सार्वजनिक कानूनी सहायता और शिकायत निवारण पोर्टल",
      heroGreeting: "नमस्ते, {name}। आज ARAM आपकी क्या सहायता कर सकता है?",
      heroDescription: "तमिल, अंग्रेजी या हिंदी में किसी भी शिकायत, कानूनी समस्या या विवाद का विवरण दें और तत्काल सत्यापित मार्गदर्शन, दस्तावेज़ आवश्यकताएं और कानूनी सहायता प्राप्त करें।",
      askLegalAssistant: "ARAM कानूनी सहायक से पूछें",
      speakGrievance: "शिकायत बोलें (आवाज़)",
      stopTranscribe: "रोकें और ट्रांसक्राइब करें",
      listening: "सुन रहा है... समाप्त करने के लिए क्लिक करें",
      cardSubmitTitle: "शिकायत दर्ज करें",
      cardSubmitDesc: "AI दस्तावेज़ विश्लेषण के साथ संरचित शिकायत दर्ज करें।",
      cardUploadTitle: "साक्ष्य अपलोड करें",
      cardUploadDesc: "OCR तत्परता से विलेख, अनुबंध और FIR सत्यापित करें।",
      cardTrackTitle: "स्थिति ट्रैक करें",
      cardTrackDesc: "प्रगति समयरेखा और कानूनी मार्गदर्शक की कार्य योजनाएं।",
      cardRightsTitle: "कानूनी अधिकार मार्गदर्शिका",
      cardRightsDesc: "DLSA संपर्क, सरकारी योजनाएं और हेल्पलाइन नंबर।",
      exploreDomainTitle: "क्षेत्र के अनुसार कानूनी अधिकार जानें",
      askAnyTopic: "कोई भी विषय पूछें >",
      domainWomenTitle: "महिला एवं परिवार कानून",
      domainWomenDesc: "भरण-पोषण, 498A, घरेलू हिंसा, बाल अभिरक्षा",
      domainLandTitle: "भूमि एवं संपत्ति",
      domainLandDesc: "पट्टा, अतिक्रमण, सीमा विवाद",
      domainConsumerTitle: "उपभोक्ता एवं RTI",
      domainConsumerDesc: "दोषपूर्ण उत्पाद, RTI आवेदन, निष्पक्ष व्यापार",
      domainLabourTitle: "श्रम एवं वेतन अधिकार",
      domainLabourDesc: "बकाया वेतन, ग्रेच्युटी, PF निपटान",
      domainCyberTitle: "आपातकालीन एवं साइबर सहायता",
      domainCyberDesc: "ऑनलाइन धोखाधड़ी, 1930 हेल्पलाइन, उत्पीड़न",
      activeGrievancesTitle: "मेरी सक्रिय शिकायतें",
      activeGrievancesDesc: "अपनी दर्ज शिकायतों और कानूनी मार्गदर्शक नोट्स को ट्रैक करें।",
      viewAllGrievances: "सभी शिकायतें देखें →",
      loadingGrievances: "आपकी शिकायतें लोड हो रही हैं...",
      noGrievancesTitle: "कोई सक्रिय शिकायत नहीं मिली।",
      noGrievancesDesc: "जब भी आप कोई शिकायत दर्ज करेंगे या कानूनी सहायता का अनुरोध करेंगे, विवरण यहां दिखाई देंगे।",
      submitFirstGrievance: "पहली शिकायत दर्ज करें"
    },
    submitComplaint: {
      headerTitle: "नागरिक शिकायत और कानूनी याचिका",
      headerSubtitle: "तमिलनाडु कानूनी सेवा प्राधिकरण • आधिकारिक शिकायत एवं निवारण रजिस्ट्री",
      aiGuidedTab: "AI-निर्देशित याचिका (5 चरण)",
      directFormTab: "सीधा फॉर्म (एकल पृष्ठ)",
      stageOf: "चरण {step} / 5",
      stageNames: {
        tellAram: "विवरण",
        aiUnderstanding: "AI समझ",
        documents: "दस्तावेज़",
        safetyGuides: "सुरक्षा और मार्गदर्शक",
        reviewSubmit: "समीक्षा और सबमिट"
      },
      stage1Title: "ARAM को बताएं क्या हुआ",
      stage1Desc: "अपनी समस्या स्वाभाविक रूप से बताएं। आप अपनी भाषा में टाइप या बोल सकते हैं।",
      tellUsLabel: "हमें बताएं क्या हुआ...",
      minChars: "न्यूनतम 15 वर्ण",
      tellUsPlaceholder: "अपने शब्दों में बताएं क्या हुआ... (आप तमिल, अंग्रेजी या हिंदी में बोल या लिख सकते हैं)",
      speakProblem: "समस्या बोलें",
      listeningClickStop: "सुन रहा है... (रोकने के लिए क्लिक करें)",
      processingSpeech: "आवाज़ संसाधित हो रही है...",
      languageLabel: "भाषा:",
      autoDetect: "✨ स्वतः पहचान",
      primaryBadge: "प्राथमिक",
      transcribedNarrative: "ट्रांसक्राइब किया गया समस्या विवरण",
      speechBadge: "{lang} वाणी",
      reviewEditTip: "✨ समीक्षा और संपादन: 'ARAM से विश्लेषण करें' पर क्लिक करने से पहले आप सीधे ऊपर दिए गए टेक्स्ट बॉक्स में नाम, राशि या तिथियां संपादित कर सकते हैं।",
      yourDistrict: "आपका जिला",
      districtHelp: "आपका जिला, ARAM को {district} जिला कानूनी सहायता डेस्क पर उचित स्थानीय सहायता से जोड़ने में मदद करता है।",
      clearText: "टेक्स्ट साफ़ करें",
      analyzingLegal: "कानूनी संदर्भ का विश्लेषण किया जा रहा है...",
      analyzeWithAram: "ARAM से विश्लेषण करें →",
      stage2Title: "ARAM AI मामला मूल्यांकन",
      listenSummary: "सारांश सुनें",
      stopAudio: "ऑडियो रोकें",
      formulatedTitle: "निर्मित समस्या शीर्षक",
      doneEditing: "संपादन पूर्ण",
      editTitle: "शीर्षक संपादित करें",
      priorityLabel: "प्राथमिकता: {priority}",
      caseOverview: "मामले की स्थिति और कानूनी अवलोकन",
      partiesIdentified: "पहचाने गए पक्ष",
      disputeClaimAmount: "विवाद दावा राशि",
      timelineDate: "समयरेखा / घटना तिथि",
      reliefQuestion: "आप क्या विशिष्ट परिणाम या राहत चाहते हैं?",
      reliefSubtitle: "आपका अनुरोधित समाधान",
      reliefPlaceholder: "उदाहरण: मैं चाहता हूं कि TNSLSA मकान मालिक को बिना किसी अवैध कटौती के मेरी ₹50,000 की सुरक्षा जमा राशि वापस करने का निर्देश दे।",
      speakBtn: "बोलें",
      recordingBtn: "रिकॉर्ड हो रहा है...",
      applicableRemedies: "लागू होने वाले कानूनी उपचार",
      backBtn: "पीछे",
      continueDocsBtn: "दस्तावेज़ और साक्ष्य पर आगे बढ़ें →",
      stage3Title: "दस्तावेज़ और सहायक साक्ष्य",
      stage3Desc: "स्वचालित तत्परता समीक्षा के लिए विलेख, नोटिस, रसीदें या अनुबंध संलग्न करें।",
      ocrIntegrityReview: "साक्ष्य तत्परता और दस्तावेज़ अखंडता समीक्षा",
      continueSafetyBtn: "सुरक्षा और सहायता पर आगे बढ़ें →",
      stage4Title: "सुरक्षा और कानूनी मार्गदर्शक प्रतिनिधित्व",
      stage4Desc: "सुरक्षा नियम निर्धारित करें और सत्यापित जिला विधिक सेवा प्राधिकरण का प्रतिनिधित्व प्राप्त करें।",
      continueReviewBtn: "समीक्षा और सबमिट पर आगे बढ़ें →",
      stage5Title: "शिकायत की समीक्षा और वैधानिक सबमिशन",
      stage5Desc: "मामला संख्या आवंटन और ब्लॉकचेन ऑडिट ब्लॉक लॉगिंग से पहले अंतिम सत्यापन।",
      declarationText: "मैं प्रमाणित करता/करती हूं कि कानूनी सहायता प्रावधानों के तहत प्रदान की गई जानकारी मेरे ज्ञान के अनुसार सत्य है।",
      submitGrievanceBtn: "कानूनी सहायता डेस्क पर शिकायत दर्ज करें →",
      submittingBtn: "कानूनी रजिस्ट्री में दर्ज किया जा रहा है...",
      successTitle: "शिकायत सफलतापूर्वक दर्ज की गई!",
      successDesc: "आपकी शिकायत तमिलनाडु कानूनी सेवा प्राधिकरण में पंजीकृत हो गई है और ब्लॉकचेन ऑडिट ब्लॉक में सुरक्षित रूप से दर्ज कर दी गई है।",
      officialRef: "आधिकारिक मामला संदर्भ संख्या:",
      trackGrievanceBtn: "शिकायत की स्थिति ट्रैक करें",
      returnDashboardBtn: "डैशबोर्ड पर लौटें"
    },
    complaintHistory: {
      title: "मेरी शिकायतों का इतिहास",
      subtitle: "दर्ज मामलों की स्थिति, साक्ष्य सत्यापन और कानूनी मार्गदर्शक नोट्स को ट्रैक करें।",
      newGrievanceBtn: "नई शिकायत दर्ज करें",
      searchPlaceholder: "शीर्षक, आईडी या विवरण द्वारा खोजें...",
      filterAll: "सभी स्थितियां",
      filterSubmitted: "दर्ज की गई",
      filterInProgress: "प्रगति पर",
      filterResolved: "समाधान हुआ",
      noComplaintsTitle: "कोई शिकायत नहीं मिली",
      noComplaintsDesc: "आपने अभी तक कोई शिकायत दर्ज नहीं की है या आपके फ़िल्टर से कोई मेल नहीं खाता।",
      fileFirstGrievance: "पहली शिकायत दर्ज करें"
    },
    evidenceVault: {
      title: "दस्तावेज़ और साक्ष्य वॉल्ट",
      subtitle: "त्वरित OCR तत्परता सत्यापन और एन्क्रिप्टेड स्टोरेज के लिए विलेख, अनुबंध और FIR अपलोड करें।",
      analyzerTitle: "OCR दस्तावेज़ कानूनी तत्परता विश्लेषक",
      analyzerSubtitle: "औपचारिक सबमिशन से पहले पंजीकरण संख्या, सीमाएं और वैधानिक मुहरों को सत्यापित करें।",
      uploadBoxTitle: "अपलोड करने के लिए क्लिक करें या फ़ाइल खींचें और छोड़ें",
      uploadBoxSubtitle: "PDF, JPG, JPEG, PNG (अधिकतम 15MB)",
      verifyBtn: "दस्तावेज़ तत्परता सत्यापित करें",
      verifyingBtn: "दस्तावेज़ OCR विश्लेषण हो रहा है...",
      readinessScore: "कानूनी तत्परता स्कोर",
      detectedEntities: "पहचाने गए कानूनी विवरण"
    },
    trackComplaint: {
      title: "शिकायत की स्थिति ट्रैक करें",
      subtitle: "समीक्षा प्रगति, आवंटित मार्गदर्शक और अगली कार्य योजना की जांच के लिए अपना ARAM केस आईडी दर्ज करें।",
      inputPlaceholder: "केस संदर्भ आईडी दर्ज करें (उदा. ARAM-2026-000001 या 1)...",
      trackBtn: "केस ट्रैक करें",
      trackingBtn: "खोज रहा है...",
      step1Title: "शिकायत दर्ज",
      step1Desc: "ARAM आधिकारिक रजिस्ट्री में सुरक्षित रूप से दर्ज की गई",
      step2Title: "AI विश्लेषण और वर्गीकरण",
      step2Desc: "लागू कानूनी धाराएं और चेकलिस्ट पहचानी गईं",
      step3Title: "कानूनी मार्गदर्शक आवंटन",
      step3Desc: "सहायता के लिए सत्यापित कानूनी मार्गदर्शक नियुक्त किया गया",
      step4Title: "प्राधिकरण समाधान",
      step4Desc: "तालुका / जिला कानूनी कार्रवाई पूर्ण हुई"
    },
    helpCenter: {
      title: "कानूनी अधिकार और आपातकालीन सहायता केंद्र",
      subtitle: "प्रमाणित वैधानिक हेल्पलाइन, जिला विधिक सेवा प्राधिकरण (DLSA) और विवाद दिशानिर्देश।",
      nalsaTitle: "राष्ट्रीय विधिक सेवा प्राधिकरण (NALSA)",
      nalsaDesc: "विधिक सेवा प्राधिकरण अधिनियम के तहत पात्र नागरिकों के लिए निःशुल्क कानूनी सहायता",
      womenTitle: "महिला हेल्पलाइन",
      womenDesc: "घरेलू हिंसा और आपातकालीन सुरक्षा के लिए 24x7 सहायता",
      cyberTitle: "राष्ट्रीय साइबर अपराध रिपोर्टिंग",
      cyberDesc: "वित्तीय धोखाधड़ी और साइबर उत्पीड़न की तत्काल रिपोर्टिंग",
      seniorTitle: "वरिष्ठ नागरिक हेल्पलाइन",
      seniorDesc: "बुजुर्गों के साथ दुर्व्यवहार और भरण-पोषण विवादों के लिए कानूनी सहायता",
      gatewayTitle: "आधिकारिक ARAM सहायता गेटवे",
      gatewayDesc: "औपचारिक याचिका प्रारूपण पूछताछ या तकनीकी सहायता के लिए ईमेल करें:"
    },
    auth: {
      layout: {
        mobileBadge: "तमिलनाडु लीगल कोपायलट",
        mobileSubtitle: "सुलभ अधिकार एवं सहायता प्रबंधन प्रणाली",
        mobileFooter: "एंड-टू-एंड एन्क्रिप्टेड • तमिलनाडु सरकार नागरिक सहायता"
      },
      banner: {
        govtTag: "तमिलनाडु सरकार एवं नागरिक सहायता",
        copilotDesc: "सुलभ अधिकार एवं सहायता प्रबंधन प्रणाली • AI कानूनी सहायक",
        slide1Badge: "सत्यापित AI कानूनी विश्लेषण",
        slide1Title: "हर नागरिक के लिए सुलभ कानूनी मार्गदर्शन",
        slide1Desc: "प्रमाणित भारतीय कानूनी ज्ञान, दंड संहिताओं और अधिनियमों के आधार पर तमिल, हिंग्लिश, हिंदी और अंग्रेजी में त्वरित विश्लेषण।",
        slide2Badge: "संस्थागत सुरक्षा",
        slide2Title: "एन्क्रिप्टेड एवं प्रत्यक्ष आधिकारिक शिकायत पंजीकरण",
        slide2Desc: "स्थानीय तालुक कार्यालयों, जिला विधिक सेवा प्राधिकरण (DLSA) और अधिवक्ताओं से सीधे जुड़ें।",
        slide3Badge: "बहुभाषी इंजन",
        slide3Title: "आवाज़-आधारित बहुभाषी पहुंच",
        slide3Desc: "तमिल, हिंदी और अंग्रेजी में अपनी मातृभाषा में बोलकर शिकायत दर्ज करें और मार्गदर्शन पाएं।",
        trust1: "सत्यापित कानूनी स्रोतों पर आधारित",
        trust2: "सत्यापित DLSA एवं तालुक समन्वय",
        trust3: "गोपनीय 256-बिट एन्क्रिप्टेड सुरक्षा",
        officialSupport: "आधिकारिक सहायता:",
        compliance: "भारतीय आईटी अधिनियम एवं DPDP 2023 के अनुरूप",
        of: "का"
      },
      login: {
        backHome: "होम पर लौटें",
        portalBadge: "एकीकृत नागरिक पोर्टल",
        title: "साइन इन",
        subtitle: "अपने कानूनी सहायता रिकॉर्ड, शिकायतें और मार्गदर्शन मामलों तक पहुंचें।",
        emailLabel: "ईमेल पता",
        emailPlaceholder: "name@example.com",
        passwordLabel: "पासवर्ड",
        passwordPlaceholder: "••••••••••••",
        forgotPassword: "पासवर्ड भूल गए?",
        rememberMe: "इस डिवाइस को 30 दिनों तक याद रखें",
        signInBtn: "खाते में साइन इन करें",
        signingIn: "साइन इन हो रहा है...",
        orContinueWith: "या इसके साथ जारी रखें",
        googleSignIn: "Google के साथ साइन इन करें",
        quickDemo: "त्वरित डेमो क्रेडेंशियल",
        hideDemo: "डेमो खाते छिपाएं",
        roleCitizen: "नागरिक",
        roleAdmin: "सेलम एडमिन",
        roleGuide: "सेलम गाइड",
        roleSuperAdmin: "सुपर एडमिन",
        demoHint: "कोई भी जिला काम करेगा: <district>.admin@gmail.com / Admin@123 & <district>.guide1@gmail.com / Admin@123",
        noAccount: "अभी तक खाता नहीं है?",
        createAccount: "मुफ्त नागरिक खाता बनाएं →",
        emailPasswordRequired: "कृपया अपना ईमेल और पासवर्ड दोनों दर्ज करें।",
        loginSuccess: "ARAM AI विधिक सहायता में पुनः स्वागत है!",
        invalidCredentials: "अमान्य ईमेल या पासवर्ड। कृपया विवरण सत्यापित करें।"
      },
      forgotPassword: {
        backSignIn: "साइन इन पर वापस जाएं",
        badge: "खाता सुरक्षा पुनर्प्राप्ति",
        title: "पासवर्ड रीसेट करें",
        subtitle: "सुरक्षित 6-अंकीय OTP प्राप्त करने के लिए अपना पंजीकृत ईमेल या 10-अंकीय मोबाइल नंबर दर्ज करें।",
        inputLabel: "ईमेल पता या मोबाइल नंबर",
        inputPlaceholder: "name@example.com या 9876543210",
        sendOtp: "सत्यापन OTP भेजें",
        sendingOtp: "OTP भेजा जा रहा है...",
        accountNotFound: "खाता नहीं मिला",
        verificationError: "सत्यापन त्रुटि",
        createNewAccount: "नया खाता बनाएं"
      },
      register: {
        backSignIn: "साइन इन पर वापस जाएं",
        badge: "आधिकारिक नागरिक पंजीकरण",
        title: "नागरिक प्रोफाइल बनाएं",
        subtitle: "AI विश्लेषण, मामला ट्रैकिंग और कानूनी सहायता के लिए तमिलनाडु विधिक सहायता नेटवर्क से जुड़ें।",
        fullName: "पूरा नाम",
        fullNamePlaceholder: "उदा. अनबरासन के",
        email: "ईमेल पता",
        emailPlaceholder: "name@example.com",
        mobile: "मोबाइल नंबर",
        mobilePlaceholder: "9876543210",
        district: "जिला",
        password: "पासवर्ड",
        confirmPassword: "पासवर्ड की पुष्टि करें",
        terms: "मैं सेवा की शर्तें और गोपनीयता नीति स्वीकार करता/करती हूं",
        submitBtn: "निःशुल्क नागरिक खाता बनाएं",
        submitting: "खाता बनाया जा रहा है...",
        alreadyAccount: "क्या आपके पास पहले से एक खाता मौजूद है?",
        signInLink: "साइन इन करें →"
      },
      otp: {
        backSignIn: "साइन इन पर वापस जाएं",
        badge: "दो-चरणीय सत्यापन",
        title: "OTP कोड सत्यापित करें",
        subtitle: "अपने पंजीकृत मोबाइल और ईमेल पर भेजा गया 6-अंकीय कोड दर्ज करें।",
        verifyBtn: "सत्यापित करें और आगे बढ़ें",
        verifying: "सत्यापित हो रहा है...",
        resendIn: "{seconds} सेकंड में पुनः भेजें",
        resendBtn: "सत्यापन कोड पुनः भेजें",
        otpRequired: "कृपया 6-अंकीय OTP कोड दर्ज करें।"
      },
      google: {
        title: "Google द्वारा साइन इन करें",
        subtitle: "ARAM में आगे बढ़ने के लिए एक खाता चुनें",
        badge: "सत्यापित आधिकारिक पहुंच",
        desc: "अपने डैशबोर्ड पर आगे बढ़ने के लिए एक खाता चुनें।",
        verifiedProfiles: "सत्यापित खाते",
        customAccount: "कस्टम Google ईमेल दर्ज करें",
        useAnother: "अन्य Google खाते का उपयोग करें",
        emailLabel: "Google ईमेल पता",
        emailPlaceholder: "yourname@gmail.com",
        nameLabel: "पूरा नाम (वैकल्पिक)",
        namePlaceholder: "उदा. आनंद कृष्णन",
        continueBtn: "इस Google खाते के साथ जारी रखें",
        verifyingBtn: "Google खाता सत्यापित हो रहा है...",
        securityNote: "भारतीय IT अधिनियम और DPDP 2023 के तहत सुरक्षित",
        continueAs: "{name} के रूप में जारी रखें",
        cancel: "रद्द करें",
        citizenBadge: "सत्यापित नागरिक",
        guideBadge: "कानूनी गाइड",
        adminBadge: "क्षेत्रीय व्यवस्थापक",
        superAdminBadge: "राज्य व्यवस्थापक"
      }
    }
  }
};

const normalizeLang = (code) => {
  if (!code) return "en-IN";
  const lower = String(code).toLowerCase();
  if (lower.startsWith("ta")) return "ta-IN";
  if (lower.startsWith("hi")) return "hi-IN";
  return "en-IN";
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return normalizeLang(localStorage.getItem("aram_lang") || "en-IN");
  });

  const changeLanguage = (newLang) => {
    const normalized = normalizeLang(newLang);
    setLanguage(normalized);
    localStorage.setItem("aram_lang", normalized);
  };

  const t = (key, fallback = "") => {
    const activeCode = normalizeLang(language);
    const langObj = translations[activeCode] || translations["en-IN"];
    const keys = key.split(".");
    let val = langObj;
    for (const k of keys) {
      if (val && typeof val === "object" && k in val) {
        val = val[k];
      } else {
        val = null;
        break;
      }
    }
    if (val !== null && val !== undefined) return val;

    let enVal = translations["en-IN"];
    for (const k of keys) {
      if (enVal && typeof enVal === "object" && k in enVal) {
        enVal = enVal[k];
      } else {
        enVal = null;
        break;
      }
    }
    return enVal !== null && enVal !== undefined ? enVal : fallback;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, availableLanguages, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    return {
      language: "en-IN",
      changeLanguage: () => {},
      availableLanguages,
      t: (key, fallback = "") => fallback
    };
  }
  return context;
};

export default LanguageContext;
