import React, { useState, useEffect } from "react";
import DashboardLayout from "@/components/layout/DashboardLayout";
import { useNavigate, useParams } from "react-router-dom";
import {
  BrainCircuit,
  ShieldCheck,
  Building2,
  BadgeAlert,
  CheckCircle2,
  Sparkles,
  ArrowLeft,
  Volume2,
  FileText
} from "lucide-react";
import { complaintService } from "../../services/complaintService";
import { toast } from "sonner";
import ReadAloudButton from "@/components/voice/ReadAloudButton";

const AIAnalysis = () => {
  const navigate = useNavigate();
  const { complaintId } = useParams();
  const [complaint, setComplaint] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchDetails = async () => {
      if (!complaintId) {
        setLoading(false);
        return;
      }
      try {
        const data = await complaintService.getComplaintById(Number(complaintId) || complaintId);
        setComplaint(data);
      } catch (err) {
        toast.error("Failed to load AI analysis details.");
      } finally {
        setLoading(false);
      }
    };
    fetchDetails();
  }, [complaintId]);

  if (loading) {
    return (
      <DashboardLayout>
        <div className="flex h-[60vh] items-center justify-center text-slate-400">
          Loading AI analysis results...
        </div>
      </DashboardLayout>
    );
  }

  // Fallback defaults if page accessed without ID
  const title = complaint?.title || "Damaged public road near bus stand";
  const desc = complaint?.description || "The complaint reports a damaged public road causing inconvenience and safety risks to local residents. AI identified this issue as a public infrastructure problem requiring Municipal Corporation intervention.";
  const category = complaint?.categoryLabel || complaint?.category || "CIVIC_INFRASTRUCTURE";
  const priority = complaint?.priority || "HIGH";
  const priorityScore = complaint?.priorityScore || 78;
  const authority = complaint?.authority || "Municipal Corporation Grievance Cell";
  const confidence = complaint?.aiResult?.confidenceScore || 96;
  const requiredDocs = complaint?.aiResult?.requiredDocuments || ["Aadhaar Card", "Grievance Letter", "Infrastructure Photos"];
  const nextSteps = complaint?.aiResult?.nextSteps || [
    "Gather supporting photos of the road damage.",
    "Draft formal complaint letter detailing Ward number.",
    "Submit petition to the local Municipal Corporation office."
  ];

  // Speech summary combination
  const speechSummary = `Complaint Category: ${category.replace("_", " ")}. Priority: ${priority}. Recommended Authority: ${authority}. Next steps: ${nextSteps.join(". ")}`;

  return (
    <DashboardLayout>
      <div className="space-y-6 max-w-4xl mx-auto">
        {/* Navigation back */}
        <div className="flex items-center justify-between border-b border-slate-100 pb-3">
          <button
            onClick={() => navigate(-1)}
            className="flex items-center gap-1.5 text-xs font-semibold text-slate-500 hover:text-slate-800 transition"
          >
            <ArrowLeft size={16} /> Back
          </button>
          <div className="flex items-center gap-2">
            <span className="text-xs text-slate-400 font-semibold uppercase">Voice Output:</span>
            <ReadAloudButton text={speechSummary} language={complaint?.language || "en-IN"} />
          </div>
        </div>

        {/* Header */}
        <div>
          <h1 className="text-2xl font-extrabold text-slate-900 tracking-tight">AI Complaint Analysis</h1>
          <p className="text-sm text-slate-500 mt-0.5">Triage category and authority recommendations generated by ARAM models.</p>
        </div>

        {/* AI Banner */}
        <div className="rounded-2xl bg-gradient-to-r from-blue-600 to-blue-700 p-6 text-white shadow-md flex items-center gap-4">
          <div className="p-3 bg-white/10 rounded-xl text-white"><BrainCircuit size={30} /></div>
          <div>
            <h2 className="text-lg font-bold">AI Analysis Completed</h2>
            <p className="text-xs text-blue-100 mt-0.5">
              Identified with {confidence}% model confidence. Review recommendations below.
            </p>
          </div>
        </div>

        {/* Summary */}
        <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm space-y-3">
          <div className="flex items-center justify-between">
            <h3 className="text-sm font-bold text-slate-800 uppercase tracking-wider">Complaint Overview</h3>
            <ReadAloudButton text={desc} language={complaint?.language || "en-IN"} />
          </div>
          <div className="rounded-xl bg-slate-50 p-4 text-xs leading-relaxed text-slate-600 border border-slate-100">
            {desc}
          </div>
        </div>

        {/* AI Cards */}
        <div className="grid gap-4 sm:grid-cols-2">
          {/* Category */}
          <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm flex items-center gap-4">
            <div className="p-3.5 rounded-xl bg-blue-50 text-blue-600"><Sparkles size={24} /></div>
            <div>
              <p className="text-[10px] text-slate-400 font-semibold uppercase tracking-wider">Predicted Category</p>
              <h3 className="text-lg font-bold text-slate-800 mt-0.5">{category.replace("_", " ")}</h3>
            </div>
          </div>

          {/* Priority */}
          <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm flex items-center gap-4">
            <div className="p-3.5 rounded-xl bg-red-50 text-red-600"><BadgeAlert size={24} /></div>
            <div>
              <p className="text-[10px] text-slate-400 font-semibold uppercase tracking-wider">Priority Level</p>
              <h3 className="text-lg font-bold text-red-600 mt-0.5">{priority} ({priorityScore} pts)</h3>
            </div>
          </div>

          {/* Department */}
          <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm flex items-center gap-4">
            <div className="p-3.5 rounded-xl bg-green-50 text-green-600"><Building2 size={24} /></div>
            <div>
              <p className="text-[10px] text-slate-400 font-semibold uppercase tracking-wider">Recommended Authority</p>
              <h3 className="text-sm font-bold text-slate-800 mt-0.5">{authority}</h3>
            </div>
          </div>

          {/* Confidence */}
          <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm flex items-center gap-4">
            <div className="p-3.5 rounded-xl bg-purple-50 text-purple-600"><ShieldCheck size={24} /></div>
            <div>
              <p className="text-[10px] text-slate-400 font-semibold uppercase tracking-wider">Classifier Confidence</p>
              <h3 className="text-lg font-bold text-purple-700 mt-0.5">{confidence}%</h3>
            </div>
          </div>
        </div>

        {/* AI Recommendations */}
        <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="text-sm font-bold text-slate-800 uppercase tracking-wider">Suggested Actions & Next Steps</h3>
            <ReadAloudButton text={nextSteps.join(". ")} language={complaint?.language || "en-IN"} />
          </div>
          <div className="grid gap-3 text-xs text-slate-600">
            {nextSteps.map((step, idx) => (
              <div key={idx} className="flex items-start gap-3 p-3 rounded-xl bg-slate-50 border border-slate-100">
                <CheckCircle2 size={16} className="text-green-600 shrink-0 mt-0.5" />
                <span>{step}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Required Documents */}
        <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="text-sm font-bold text-slate-800 uppercase tracking-wider">Required Evidence Checklist</h3>
            <ReadAloudButton text={`Required documents: ${requiredDocs.join(", ")}`} language={complaint?.language || "en-IN"} />
          </div>
          <div className="grid gap-3 sm:grid-cols-3">
            {requiredDocs.map((doc, idx) => (
              <div key={idx} className="p-4 rounded-xl bg-blue-50/50 border border-blue-100 flex items-center gap-2.5">
                <FileText size={18} className="text-blue-600 shrink-0" />
                <span className="text-xs font-semibold text-slate-700">{doc}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Actions */}
        <div className="flex justify-end gap-3 pt-4 border-t border-slate-100">
          <button
            type="button"
            onClick={() => navigate("/citizen/history")}
            className="rounded-xl border border-slate-200 bg-white px-6 py-2.5 text-xs font-bold text-slate-600 hover:bg-slate-50 transition active:scale-95"
          >
            VIEW COMPLAINT STATUS
          </button>
          <button
            type="button"
            onClick={() => navigate("/citizen/dashboard")}
            className="rounded-xl bg-blue-600 px-6 py-2.5 text-xs font-bold text-white shadow-md hover:bg-blue-700 transition active:scale-95"
          >
            RETURN TO DASHBOARD
          </button>
        </div>
      </div>
    </DashboardLayout>
  );
};

export default AIAnalysis;